export const KLEMMI_AUDIO_ROUTE = "/api/klemmi/audio";

/** Einheitliche Markenstimme für alle bestehenden und zukünftigen Klemmi-Touren. */
export const KLEMMI_VOICE_PROFILE = {
  voice: "Achird",
  label: "Klemmi – warm und organisatorisch",
  description:
    "Freundliche männliche Cartoon-Stimme: warm, klar, leicht verspielt und strukturiert.",
} as const;

/**
 * Feste, vorproduzierte Klemmi-Texte. Die Dateien liegen ausschließlich im
 * Produkt-Container und werden erst ausgeliefert, wenn eine Tour bewusst
 * geöffnet wurde. Es werden keine Eingaben oder personenbezogenen Daten an
 * einen Sprachdienst übertragen.
 */
export const KLEMMI_AUDIO_SCRIPTS = {
  "opening-clears-throat": "[clears throat] So, los geht's!",
  "opening-cough": "[cough] Hups, kurz sortiert. Jetzt aber!",
  "opening-sniff": "[sniffs] Alles klar, ich bin bereit!",
  "opening-ach-herrje": "Ach herrje, da bin ich ja!",
  "opening-servus": "Servus, Klemmi ist da!",
  "opening-gruess-gott": "Grüß Gott, schauen wir gemeinsam drauf!",
  "opening-hallo": "Hallo, ich helfe dir gern!",
  "opening-na-dann": "Na dann, legen wir los!",
  "opening-auf-gehts": "Auf geht's, ich bin dabei!",
  "opening-moin": "Moin, Klemmi ist startklar!",
  "opening-halloechen": "Hallöchen, schön, dass du da bist!",
  "opening-tadaa": "Tadaa, dein Klemmi ist da!",
  "opening-na-schau-an": "Na, schau an, dann gucken wir mal!",
  "opening-guten-tag": "Guten Tag, worum kümmern wir uns?",
  "opening-klingeling": "Klingeling, Klemmi meldet sich!",
  "opening-hmm": "Hmm, schauen wir mal.",
  "opening-jawohl": "Jawohl, ich bin zur Stelle!",
  "opening-aha": "Aha, das kriegen wir hin!",
  "opening-hey-ho": "Hey ho, Klemmi übernimmt!",
  "opening-na-endlich": "Na endlich, los geht's!",
  "opening-hoi": "Hoi, ich bin schon da!",
  "opening-bitte-sehr": "Bitte sehr, deine Hilfe ist da!",
  "opening-wir-packen-das": "Keine Sorge, wir packen das!",
  "opening-einen-moment": "Einen kleinen Moment, ich bin ganz Ohr!",
  "opening-hopp-hopp": "Hopp hopp, schauen wir rein!",
  "opening-zack": "Zack, Klemmi ist bereit!",
  "opening-lass-uns-schauen": "Lass uns gemeinsam schauen!",
  "opening-alles-klar": "Alles klar, ich zeig's dir!",
  "opening-ganz-entspannt": "Ganz entspannt, wir gehen das zusammen an!",
  "opening-wunderbar": "Wunderbar, dann starten wir!",

  "first-login-intro": "Hallo! Ich bin Klemmi. Und nein – nicht weil ich verklemmt bin. [laughing] Sondern weil ich immer genau dann zur Stelle bin, wenn es irgendwo klemmt, oder halt, wenn du das erste Mal hier bist! Egal ob Schichten, Helfer oder Event-Planung: Wenn du mal nicht weiterweißt, klick mich einfach an! Du findest mich ab jetzt auf jeder Seite ganz oben im Menü.",
  "first-login-co-admin": "Hallo! Ich bin Klemmi. Und nein – nicht weil ich verklemmt bin. [laughing] Sondern weil ich immer genau dann zur Stelle bin, wenn es irgendwo klemmt, oder halt, wenn du das erste Mal hier bist! Egal ob Schichten, Helfer oder Event-Planung: Wenn du mal nicht weiterweißt, klick mich einfach an! Du findest mich ab jetzt auf jeder Seite ganz oben im Menü. Und noch ein Tipp für dich als Co-Admin: Im nächsten Schritt siehst du deine wichtigsten Rechte. Die vollständige Rechte-Matrix findest du später jederzeit im Hilfe-Bereich.",
  "login-warmgelaufen": "Da bist du ja wieder! Ich hab die Tabellen schon mal warmgelaufen. Wo legen wir los?",
  "login-chaos": "Servus! Bereit, das Chaos in geordnete Bahnen zu lenken? Ich wär's jedenfalls!",
  "login-ehrenamt": "Eingeloggt und startklar! Lass uns das Ehrenamt mal wieder ein bisschen einfacher machen.",
  "login-aermel": "Hey! Schön, dass du da bist. Ich hab schon mal die Ärmel hochgekrempelt – wenn ich welche hätte!",
  "login-kaffee": "Kaffee steht bereit, System ist hochgefahren. Dann zeig mal, was für ein Event-Genie in dir steckt!",
  "login-tabellen": "Zurück am Drücker! Lass uns ein paar Aufgaben wegzaubern – ganz ohne Magie, nur mit System!",
  "login-druecker": "Zurück am Drücker! Welche Aufgabe knacken wir heute zuerst?",
  "login-noch-eins": "Endlich Verstärkung! Ich dachte schon, ich muss die Schichten ganz alleine rocken.",
  "login-datenbank": "Na, wer klopft denn da an die Datenbank? Lass uns ein paar Haken auf die To-do-Liste setzen!",
  "login-system": "Welcome back! Das System läuft geschmeidig, der Klemmi ist wach. Wo packen wir als Erstes an?",
  "login-superhelden": "Wer braucht schon Superhelden, wenn wir deinen Login-Button haben? Welchen Plan retten wir heute?",
  "login-roter-teppich": "Da ist ja der Star des Vereins! Ich hab den roten Teppich im Dashboard schon ausgerollt.",

  "idle-vorstehhund": "Ich stehe bereit wie ein Vorstehhund. Sag mir einfach, wo ich hinspringen soll!",
  "idle-kaffee": "Mein virtueller Kaffee wird kalt. Sollen wir weitermachen?",
  "idle-standbild": "Standbild oder Denkpause? Ich warte geduldig, aber nicht zu geschniegelt.",
  "idle-wuerstchenbude": "In der Zeit, die du überlegst, hätte ich fast eine Würstchenbude organisiert!",
  "idle-singen": "Wenn hier gar nichts passiert, fange ich an zu singen. Das willst du nicht.",

  "error-halt-stopp": "Halt, stopp, fast perfekt. Da fehlt noch was.",
  "error-fast-perfekt": "Fast perfekt! Ein kleines Feld fehlt noch, dann bist du durch.",
  "error-zauberei": "Das Feld füllt sich leider nicht mit Zauberei. Hilfst du kurz nach?",
  "error-rotes-feld": "Das rote Feld winkt schon. Einmal kurz ergänzen, bitte.",
  "error-verrats-keinem": "Ich verrat's keinem, aber dieses Feld braucht noch Inhalt.",
  "error-kleingedrucktes": "Wer liest schon Kleingedrucktes? Ich. Und da fehlt noch eine Kleinigkeit.",
  "error-knapp-vorbei": "Netter Schuss, aber knapp am Ziel vorbei. Schau noch mal auf das markierte Feld.",
  "error-schranke": "So lassen wir dich nicht durch die Schranke. Eine Angabe fehlt noch, Meister!",

  "success-zack": "Zack! Wieder eine Schicht eingetütet.",
  "success-boom": "Boom! Schicht steht. Stark gemacht!",
  "success-volltreffer": "Volltreffer! Die Lücke im Plan ist Geschichte.",
  "success-reibungslos": "Reibungslos eingeteilt. So macht Planung Laune!",
  "success-baem": "Bäm! Besser hätte das kein Profi-Disponent gemacht.",
  "success-leerstand": "Tschüss Leerstand, hallo Helfer!",
  "success-bilderbuch": "Eine Schicht wie aus dem Bilderbuch.",
  "success-bingo": "Bingo! Wieder ein Helfer glücklich untergebracht.",
  "success-high-five": "High Five! Die Schicht ist bombensicher versorgt.",
  "success-passt": "Passt, wackelt und hat Luft. Nächste Schicht?",
  "success-geschmiert": "Läuft wie geschmiert! Ich komme mit dem Mitschreiben kaum nach.",
  "success-arbeitslos": "Wieder ein Häkchen mehr. Du machst mich noch arbeitslos!",
  "package-tip-event-pass": "Du planst eine einzelne Veranstaltung schlank und klar. Mit Light kommen Ansprechpartner, wiederverwendbare Orte, Material und ein kleines Planungsteam dazu.",
  "package-tip-light": "Du organisierst bereits gemeinsam im kleinen Team. Mit Pro ergänzt ihr Chat, Spenden, Finanzen, Live-Karten und individuelle WhatsApp-Vorlagen.",
  "package-tip-pro": "Ihr nutzt die vollständige Vereinsplanung. Enterprise passt Mengen, Abläufe und Erweiterungen an euren individuellen Vereins- oder Verbandsbedarf an.",
  "dashboard-intro": "Dein Dashboard auf einen Blick. Hier laufen die Informationen aus deiner Planung zusammen. Ich zeige dir jetzt nur die Bereiche, die auf diesem Dashboard wirklich sichtbar sind.",
  "dashboard-countdown-dated": "Countdown bis zum Event. Hier siehst du den Zeitraum der aktuellen Veranstaltung und den Countdown. Das Datum kommt direkt aus den Eventdaten und aktualisiert sich automatisch.",
  "dashboard-countdown-empty": "Zeitraum für den Countdown festlegen. Hier erscheint der Countdown, sobald du in den Eventdaten einen Start- und bei mehrtägigen Veranstaltungen auch einen Endtermin speicherst.",
  "dashboard-priorities-attention": "Was jetzt Aufmerksamkeit braucht. Diese Karten zeigen nur konkrete Warnungen oder offene Punkte, zum Beispiel unbesetzte Schichten, Ausfälle oder offene Vorbereitungen. Ein Klick führt direkt in den passenden Bereich.",
  "dashboard-priorities-clear": "Keine dringenden Punkte. Hier werden später nur Punkte eingeblendet, die unmittelbar Aufmerksamkeit brauchen. Sobald es offene Schichten, Konflikte oder Aufgaben gibt, erscheinen sie automatisch an dieser Stelle.",
  "dashboard-deadlines": "Datierte Vorbereitungsaufgaben. Diese Übersicht erscheint, wenn Vorbereitungsaufgaben ein Fälligkeitsdatum haben. Du siehst die nächsten Termine zuerst und öffnest per Klick direkt die zugehörige Aufgabe.",
  "dashboard-helpers-active": "Helferstatus je Festivaltag. Hier erkennst du pro Veranstaltungstag Besetzung und Bedarf, Rückmeldungen, Erstkontakte und Verpflegungsspenden. Klickbare Werte führen in die bereits passend gefilterte Helfer- oder Einsatzplanansicht.",
  "dashboard-helpers-empty": "Helferstatus entsteht mit deiner Planung. Sobald du Helfer anlegst und Schichten mit Bedarf planst, erscheinen hier Besetzung, Rückmeldungen und Erstkontakte. Erfasste Kuchen- und Salatspenden werden daneben automatisch zusammengefasst.",
  "dashboard-details-active": "Wer macht was – und wer ist frei? Links siehst du Verantwortlichkeiten nach Ansprechpartnern. Rechts zeigt die Helferauslastung alle eingeteilten Schichten je Tag. Ein Klick auf einen Namen oder Wert öffnet die passende gefilterte Einsatzplanung.",
  "dashboard-details-active-stacked": "Wer macht was – und wer ist frei? Oben siehst du Verantwortlichkeiten nach Ansprechpartnern. Darunter zeigt die Helferauslastung alle eingeteilten Schichten je Tag. Ein Klick auf einen Namen oder Wert öffnet die passende gefilterte Einsatzplanung.",
  "dashboard-details-empty": "Details wachsen mit den Einträgen. Hier entstehen zwei Übersichten, sobald Ansprechpartner, Helfer und Schichten gepflegt sind: Zuständigkeiten auf der linken Seite und die tägliche Helferauslastung auf der rechten Seite.",
  "dashboard-details-empty-stacked": "Details wachsen mit den Einträgen. Hier entstehen zwei Übersichten, sobald Ansprechpartner, Helfer und Schichten gepflegt sind: Zuerst die Zuständigkeiten nach Ansprechpartnern und direkt darunter die tägliche Helferauslastung.",
  "dashboard-map-active": "Live-Standortkarte nutzen. Diese Karte verbindet Orte mit Vorbereitung, Schichten und Material. Die Farben zeigen den jeweiligen Stand, und ein Klick auf einen Marker filtert den passenden Planungsbereich.",
  "dashboard-map-empty": "Standortkarte später aktivieren. Sobald du unter Orte und Standorte mindestens einen Standort mit Koordinaten anlegst, wird hier unten automatisch die Live-Standortkarte mit den zugehörigen Planungsinformationen eingeblendet.",
  "dashboard-complete": "Alles im Blick! Du weißt jetzt, wo das Dashboard den aktuellen Planungsstand zeigt – und welche Eingaben die einzelnen Übersichten füllen.",
  "dashboard-map-locked": "Live-Standortkarte ab Pro. Die Live-Standortkarte mit GPS-Orten, Strecken und Statusmarkern steht ab Pro bereit. Im Event Pass konzentrierst du dich auf Helfer, Einsatzplan, Vorbereitung und die Standard-PDFs. Deshalb wird hier keine Karte eingeblendet.",
  "dashboard-map-locked-light": "Live-Standortkarte ab Pro. Im Light-Paket kannst du Orte und Standorte bereits für Schichten, Vorbereitung und Material nutzen. Die interaktive Karte mit GPS-Punkten, Strecken und Statusmarkern ergänzt Pro. Deshalb wird auf diesem Dashboard noch keine Karte eingeblendet.",
  "dashboard-helpers-active-no-donations": "Helferstatus je Festivaltag. Hier erkennst du pro Veranstaltungstag Besetzung und Bedarf, Rückmeldungen und Erstkontakte. Klickbare Werte führen in die bereits passend gefilterte Helfer- oder Einsatzplanansicht.",
  "dashboard-helpers-empty-no-donations": "Helferstatus entsteht mit deiner Planung. Sobald du Helfer anlegst und Schichten mit Bedarf planst, erscheinen hier Besetzung, Rückmeldungen und Erstkontakte. So siehst du frühzeitig, wo noch Rückmeldungen oder Helfer fehlen.",

  "helpers-intro": "Neue Helfer sicher anlegen. Ich führe dich direkt auf der echten Oberfläche durch die Anlage – vom Namen bis zum passenden Zeitfenster.",
  "helpers-overview": "Hier beginnt ein neuer Helfer. Du startest immer in der Helferübersicht. Über den markierten Button Neuer Helfer öffnest du die Anlage für eine neue Person. Ich zeige dir jetzt zuerst den Weg dorthin und öffne anschließend nur eine leere Eingabe – gespeichert wird dabei nichts.",
  "helpers-person": "Mit einem eindeutigen Namen beginnen. Der Name ist die einzige Pflichtangabe und sorgt dafür, dass das Planungsteam die Person in Helferliste, Einsatzplan und persönlicher PDF eindeutig wiederfindet. Diese Führung öffnet nur die leere Anlage – sie speichert nichts.",
  "helpers-contact": "Kontaktwege für Rückfragen ergänzen. Ansprechpartner und Telefonnummer sind optional, aber sehr hilfreich: Das Team weiß, wer zuständig ist und kann den Helfer bei einer Rückfrage oder kurzfristigen Änderung direkt erreichen.",
  "helpers-contact-event-pass": "Fest dem Hauptadministrator zugeordnet. Im Event Pass wird jeder Helfer automatisch dem Hauptadministrator als fester Ansprechperson zugeordnet. Weitere Ansprechpartner und die freie Zuordnung ergänzen das Light-Paket. Die Telefonnummer bleibt weiterhin optional und kann direkt hier gepflegt werden.",
  "helpers-details": "Hinweise und Begleitung festhalten. Besondere Hinweise erscheinen später in der persönlichen Helfer-PDF. Eine Begleitung wird im Einsatzplan sichtbar, damit das Team bei der Schichtplanung genau weiß, wer zusätzlich mitkommt.",
  "helpers-availability-entry": "Verfügbarkeit direkt erfassen. Dieser Abschnitt ist optional. Ja bedeutet ganztägig planbar. Ja mit Uhr öffnet ein Zeitfenster von bis. Nein schützt vor einer falschen Einteilung. Unklar heißt: Die Rückmeldung fehlt noch, also bitte noch nicht verbindlich einplanen. Ohne Auswahl bleibt jeder aktive Tag zunächst auf Unklar.",
  "helpers-donation": "Spende direkt mit erfassen. Wenn jemand Kuchen, Salat, Snacks oder eine andere Spende zusagt, öffnet dieses Feld die vollständige Spendenerfassung. So bleiben Verpflegung, Eigenschaften und Absprachen von Anfang an beim richtigen Helfer nachvollziehbar.",
  "helpers-donation-locked": "Spenden ab Pro verwalten. Hier kannst du Sach- und Kuchenspenden erfassen. Hinweis: Die Spendenverwaltung ist ab dem Paket Pro verfügbar.",
  "helpers-save": "Erst speichern – dann kann das Team planen. Mit Helfer anlegen oder Helfer und Spende anlegen wird die Person vollständig übernommen. Erst danach steht sie dem Planungsteam im Einsatzplan zur Auswahl. Für diese Erklärung musst du den Button nicht drücken.",
  "helpers-save-locked": "Helfer speichern, dann kann das Team planen. Mit Helfer anlegen wird die Person vollständig übernommen. Erst danach steht sie dem Planungsteam im Einsatzplan zur Auswahl. Die gemeinsame Anlage einer Spende ergänzt das Pro-Paket. Für diese Erklärung musst du den Button nicht drücken.",
  "helpers-availability": "Verfügbarkeit später nachpflegen. Nach dem Speichern bleiben dieselben Tagesverfügbarkeiten direkt an der Helferkarte bearbeitbar. Ja bedeutet ganztägig planbar; die Uhr zeigt ein begrenztes Zeitfenster. Nein schützt vor einer falschen Einteilung, Unklar wartet auf Rückmeldung.",
  "helpers-plan-fill": "Das Team füllt danach die passenden Schichten. Sobald Helfer gespeichert und Verfügbarkeiten gepflegt sind, teilt das Planungsteam sie im Einsatzplan den offenen Schichten zu. Tageszeichen, Zeitfenster, Begleitungen und bereits belegte Einsätze helfen dabei, Überlappungen zu vermeiden.",
  "helpers-feedback": "Erst die Antwort macht die Besetzung verbindlich. Antwortet der Helfer, trägt das Team Helfen: Ja oder Nein ein und setzt die Bestätigung passend zur Rückmeldung. Nur bestätigte Zusagen machen sichtbar, welche Schichten wirklich sicher sind.",
  "helpers-symbols-offer": "Geschafft! Du hast einen Helfer angelegt und die Verfügbarkeit kennengelernt. Soll ich dir auch noch die Symbole direkt an diesem Helfer erklären?",
  "helpers-action-donation": "Geschenk: Spenden dieses Helfers. Das Geschenk ganz links öffnet die Spendenübersicht genau für diese Person. Dort lassen sich Kuchen, Salate oder Snacks mit Eigenschaften und Hinweisen erfassen und später wiederfinden.",
  "helpers-action-donation-locked": "Geschenk: Spenden ab Pro. Das Geschenke-Symbol steht für Spenden, zum Beispiel Kuchen oder Snacks. Das Schloss zeigt: Die Spendenverwaltung wird ab dem Paket Pro freigeschaltet. Helfer, Verfügbarkeiten und Einsatzplan bleiben vollständig nutzbar.",
  "helpers-action-whatsapp": "Nach vollständiger Planung per WhatsApp anfragen. Ist der Einsatzplan für diesen Helfer fertig, öffnet das grüne Symbol die passende WhatsApp-Vorlage. Die Nachricht kann den persönlichen Helferplan mit PDF-Link enthalten und bittet verbindlich um Rückmeldung. In dieser Tour wird nichts versendet.",
  "helpers-action-whatsapp-locked": "Direkt schreiben, Vorlagen ab Pro. Über den WhatsApp-Button kannst du Helfern direkt schreiben. Automatische Textvorlagen stehen ab dem Paket Pro bereit. In deiner aktuellen Version tippst du die Nachricht einfach selbst ein.",
  "helpers-action-pdf": "Persönlichen Helferplan als PDF bereitstellen. Das blaue Symbol erzeugt die persönliche Aufgaben-PDF mit Einsätzen, Hinweisen und Verfügbarkeiten. Sie kann nach der Planung heruntergeladen oder über die WhatsApp-Vorlage verlinkt werden. In dieser Erklärung wird nichts heruntergeladen.",
  "helpers-action-edit": "Daten später sauber nachpflegen. Der Stift öffnet die Bearbeitung. Telefonnummer, Ansprechpartner, Hinweis, Begleitung und Verfügbarkeiten können hier später ergänzt oder geändert werden, ohne den bisherigen Einsatzplan zu verlieren.",
  "helpers-action-delete": "Der Papierkorb wird nur rot und anklickbar angezeigt, wenn dieser Helfer gelöscht werden darf. Bei geschützten oder eingeteilten Personen bleibt er grau. So kann nichts versehentlich verloren gehen.",
  "helpers-complete": "Der Ablauf ist klar: Helfer speichern, Verfügbarkeiten pflegen, Schichten passend füllen, den persönlichen Plan senden und die Antwort verbindlich eintragen – so bleibt der Einsatzplan zuverlässig.",

  "contacts-intro": "Ansprechpartner von Anfang an pflegen. Ansprechpartner sind deine verlässlichen Kontaktpersonen für Teams, Helfer und PDFs. Ich führe dich kurz durch die Stammdatenanlage.",
  "contacts-name": "Name eindeutig eintragen. Trage zuerst den Namen ein. Diese Angabe ist erforderlich und erscheint später bei Zuordnungen, in Listen und in persönlichen Unterlagen.",
  "contacts-details": "E-Mail und Rufnummer ergänzen. E-Mail-Adresse und Rufnummer sind optional, aber für Rückfragen besonders hilfreich. Ein persönlicher Zugang wird bewusst getrennt unter Schutz und Protokoll eingerichtet.",
  "contacts-save": "Ansprechpartner hinzufügen. Klicke auf den markierten Button. Danach steht die Person direkt für Helfer, Aufgaben und Zuständigkeiten zur Auswahl bereit.",
  "contacts-complete": "Geschafft! Der Ansprechpartner ist angelegt und kann jetzt überall in der Planung zugeordnet werden.",

  "donations-intro": "Spenden übersichtlich erfassen. Kuchen, Salate und andere Verpflegungsspenden werden hier sauber mit Spender, Eigenschaften und Abgabe organisiert. Ich zeige dir alles. Du musst dafür nichts eintragen oder speichern.",
  "donations-donor": "Spender zuordnen. Wähle einen bestehenden Helfer aus oder trage einen Namen frei ein. So bleibt nachvollziehbar, von wem die Spende kommt.",
  "donations-item": "Spende und Kategorie festlegen. Beschreibe kurz, was mitgebracht wird, und wähle die passende Kategorie. So bleibt der Überblick über Kuchen, Salate, Desserts und Sonstiges erhalten.",
  "donations-traits": "Allergene, Abgabe und Hinweise. Kennzeichne bei Bedarf vegan, glutenfrei, laktosefrei, Nüsse oder fleischhaltig. Abgabeort, Zeitpunkt und ein freier Hinweis helfen der Verpflegung am Veranstaltungstag.",
  "donations-save": "Spende speichern. Mit dem markierten Speichern-Button wird die Spende in die Übersicht übernommen und zählt automatisch für die aktuelle Veranstaltung. Für diese Erklärung klickst du nicht auf Speichern.",
  "donations-overview": "Spendenübersicht lesen. Nach dem Speichern erscheint jede Spende mit Spender, Kategorie, Eigenschaften, Abgabeort und Zeitpunkt. So sieht das Verpflegungsteam sofort, was zugesagt wurde und welche Hinweise wichtig sind.",
  "donations-filters": "Gezielt nach Spenden suchen. Mit Kategorie, Eigenschaften, Abgabetag, Standort und Suche filterst du die Liste. Das ist besonders hilfreich, wenn kurz vor dem Event nur vegane Kuchen, eine bestimmte Abgabezeit oder ein Standort geprüft werden soll.",
  "donations-outputs": "Übersicht drucken oder Ansicht wechseln. Der PDF-Druck erstellt eine kompakte Übersicht der aktuell sichtbaren Spenden. Mit Liste und Kacheln wählst du einfach die Darstellung, die für deine Arbeit gerade am besten passt. In dieser Tour wird nichts gedruckt oder verändert.",
  "donations-complete": "Spenden im Griff! Du weißt jetzt, wie eine Spende erfasst, in der Übersicht wiedergefunden, gefiltert und für das Verpflegungsteam ausgegeben wird.",

  "finances-intro": "Finanzen einfach im Blick behalten. Hier werden Einnahmen und Ausgaben nach Kategorien getrennt geführt. Der Saldo wird für dich automatisch berechnet.",
  "finances-category": "Kostenart anlegen. Trage eine klare Kategorie ein, zum Beispiel Startgelder, Catering, Technik oder Sponsoring. Mit dem Button daneben wird die neue Zeile angelegt.",
  "finances-save": "Kategorie übernehmen. Klicke auf den markierten Button. Erst dann wird die Kategorie wirklich angelegt und du kannst Einnahmen und Ausgaben eintragen.",
  "finances-values": "Einnahmen und Ausgaben eintragen. In jeder Kategorie gibst du Einnahmen und Ausgaben ein. Die Werte werden beim Verlassen des Feldes gespeichert; die Differenz zeigt sofort den aktuellen Stand.",
  "finances-balance": "Saldo gemeinsam prüfen. Ganz unten fasst der Saldo alle Kategorien zusammen. So erkennst du schnell, ob deine Veranstaltung finanziell im Plan liegt.",
  "finances-complete": "Alles klar! Du weißt jetzt, wo Kategorien, Einzelwerte und der gesamte Saldo zusammenkommen.",

  "marketing-intro": "Marketingmaßnahmen verständlich planen. Ich zeige dir, wie du eine Maßnahme mit Kanal, Status und Verantwortlichkeit planst und in der Übersicht nachhältst.",
  "marketing-name": "Maßnahme klar benennen. Trage ein, was veröffentlicht oder organisiert werden soll, zum Beispiel Pressemitteilung, Plakataktion oder Social-Media-Beitrag.",
  "marketing-details": "Kanal und Zuständigkeit einordnen. Der Kanal macht sofort klar, wo die Maßnahme stattfindet. Verantwortliche und Status helfen dem Team, die Umsetzung verlässlich nachzuhalten.",
  "marketing-save": "Maßnahme speichern. Mit dem markierten Button wird die Marketingmaßnahme in die Planung übernommen.",
  "marketing-complete": "Marketing im Blick! Du weißt jetzt, wie Maßnahmen angelegt, nachverfolgt und bei Bedarf wieder entfernt werden.",

  "approvals-intro": "Genehmigungen nachvollziehbar verwalten. Ich zeige dir, wie du einen Antrag erfasst, seinen Status pflegst und in der Übersicht den aktuellen Stand abliest.",
  "approvals-name": "Antrag eindeutig benennen. Trage klar ein, welche Genehmigung gebraucht wird, zum Beispiel Straßensperrung, GEMA oder Sanitätsdienst. So ist der Vorgang später sofort wiederzufinden.",
  "approvals-save": "Antrag speichern. Mit dem markierten Button wird der Antrag in die Genehmigungsübersicht übernommen.",
  "approvals-complete": "Genehmigungen im Blick! Du weißt jetzt, wie ein Antrag angelegt, sein Status nachgeführt und ein nicht mehr benötigter Eintrag entfernt wird.",

  "preparation-overview-save": "Der markierte Button legt eine neue Aufgabe an. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt die vorhandene Vorbereitungsübersicht.",
  "preparation-overview": "Vorbereitung im Überblick. Du kennst jetzt die vorhandenen Aufgaben und kannst sie filtern, bearbeiten oder bei Bedarf entfernen.",
  "postprocessing-overview-save": "Der markierte Button legt eine neue Aufgabe an. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt die vorhandene Nachbereitungsübersicht.",
  "postprocessing-overview": "Nachbereitung im Überblick. Du kennst jetzt die vorhandenen Aufgaben und kannst sie filtern, bearbeiten oder bei Bedarf entfernen.",
  "materials-overview-save": "Der markierte Button legt einen neuen Artikel an. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt den vorhandenen Materialplan.",
  "materials-overview": "Material im Überblick. Du kennst jetzt die vorhandenen Artikel und kannst sie filtern, bearbeiten oder bei Bedarf entfernen.",
  "marketing-overview-save": "Der markierte Button legt eine neue Maßnahme an. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt die vorhandene Marketingübersicht.",
  "marketing-overview": "Marketing im Überblick. Du kennst jetzt die vorhandenen Maßnahmen und kannst sie filtern, bearbeiten oder bei Bedarf entfernen.",
  "approvals-overview-save": "Der markierte Button legt einen neuen Antrag an. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt die vorhandene Genehmigungsübersicht.",
  "approvals-overview": "Genehmigungen im Überblick. Du kennst jetzt die vorhandenen Anträge und kannst ihren Status pflegen oder bei Bedarf entfernen.",
  "locations-overview-save": "Der markierte Button legt einen neuen Standort an. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt die vorhandenen Orte.",
  "locations-overview": "Standorte im Überblick. Du kennst jetzt die vorhandenen Orte und kannst Name oder Koordinaten anpassen oder einen nicht mehr benötigten Ort entfernen.",
  "contacts-overview-save": "Der markierte Button legt einen neuen Ansprechpartner an. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt die vorhandenen Stammdaten.",
  "contacts-overview": "Ansprechpartner im Überblick. Du kennst jetzt die vorhandenen Kontaktpersonen und kannst ihre Stammdaten bei Bedarf bearbeiten oder entfernen.",
  "donations-overview-save": "Der markierte Button speichert eine neue Spende. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt die vorhandene Spendenübersicht.",
  "donations-overview-summary": "Spenden im Überblick. Du kennst jetzt die vorhandenen Spenden mit Eigenschaften, Abgabeort und Zeitpunkt und kannst sie bei Bedarf bearbeiten oder entfernen.",
  "finances-overview-save": "Der markierte Button legt eine neue Kategorie an. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt die bereits gepflegten Werte.",
  "finances-overview": "Finanzen im Überblick. Du kennst jetzt die vorhandenen Kategorien, ihre Werte und den Saldo und kannst alles bei Bedarf anpassen.",

  "pdf-intro": "Passende PDFs gezielt erstellen. In der PDF-Ausgabe erzeugst du persönliche Helferunterlagen, Ansprechpartnerübersichten und gefilterte Einsatzpläne aus den realen Planungsdaten.",
  "pdf-helpers": "Helfer-PDFs bündeln. Wähle bei Bedarf einen Ansprechpartner aus. Anschließend erzeugst du entweder alle Helfer-PDFs als ZIP oder nur die passenden Unterlagen für diese Person.",
  "pdf-plan": "Einsatzplan filtern und drucken. Für den Einsatzplan wählst du Tag, Bereiche, Status und bei Bedarf Ansprechpartner. Das PDF enthält nur die Auswahl, die du wirklich brauchst.",
  "pdf-config": "Vorlage pro Veranstaltung pflegen. Administratoren können hier Logo, Titel, Zusatzspalten, Fußzeilen und WhatsApp-Vorlagen für die aktuell gewählte Veranstaltung konfigurieren. Andere sehen die fertigen PDFs weiterhin unverändert.",
  "pdf-complete": "Fertig! Damit kannst du genau die Unterlagen erzeugen, die dein Team gerade braucht.",
  "pdf-intro-event-pass": "Passende PDFs gezielt erstellen. Im Event Pass erzeugst du persönliche Helferunterlagen und gefilterte Einsatzpläne aus den realen Planungsdaten. Ansprechpartner-Arbeitsmappen erkläre ich dir gleich als Light-Erweiterung.",
  "pdf-plan-event-pass": "Einsatzplan filtern und drucken. Für den Einsatzplan wählst du Tag, Bereiche und Status. Das PDF enthält nur die Auswahl, die du wirklich brauchst. Eine Ansprechpartnerauswahl steht ab Light bereit.",
  "pdf-config-light": "PDF-Vorlage im Light-Paket pflegen. Titel, Zusatzspalten, Hinweise und Fußzeilen kannst du hier für die aktuelle Veranstaltung konfigurieren. Ein eigenes Eventlogo und automatische WhatsApp-Vorlagen ergänzen das Pro-Paket. Bis dahin bleibt das MyCrewMate-Logo aktiv und WhatsApp öffnet einen leeren Chat für freie Nachrichten.",

  "security-intro": "Schutz und Protokoll für Administratoren. Hier regelst du die sichersten Einstellungen deines Vereins: Administratorpasswort, persönliche Planungsteam-Zugänge, Notfall-Stopp und nachvollziehbare Protokolle. Die Führung öffnet nur Ansichten – sie ändert nichts.",
  "security-password": "Administratorpasswort sicher neu vergeben. Dieser Bereich ist nur für den Hauptadministrator sichtbar. Zur Neuvergabe bestätigst du zuerst das aktuelle Administratorpasswort, wählst anschließend mindestens zehn Zeichen und wiederholst die Eingabe. So kann niemand mit einer offenen Sitzung das zentrale Passwort heimlich ändern.",
  "security-accesses-overview": "Planungsteam-Zugänge gezielt verwalten. Jede Person erhält einen eigenen Zugang. Dadurch lassen sich Rechte, freigegebene Veranstaltungen und Änderungen sauber der richtigen Person zuordnen. Gemeinsame Passwörter solltest du vermeiden – sie machen Verantwortlichkeiten und spätere Anpassungen unnötig schwer.",
  "security-accesses-filter": "Vorhandene Zugänge mit Filtern prüfen. Hier begrenzt du die Übersicht auf ein Jahr oder eine Veranstaltung. Das ist hilfreich, wenn dein Verein mehrere Events plant: Du erkennst sofort, welche Personen für die gewählte Veranstaltung zugelassen sind, und musst nicht durch alle Zugänge suchen.",
  "security-accesses-list": "Status und Freigaben einer Person lesen. Jede Zugangskarte zeigt Name, E-Mail, Passwortstatus, Rolle, sichtbare Fachbereiche und freigegebene Veranstaltungen. Grün bedeutet: Passwort eingerichtet. Gelb bedeutet: Der Initialcode ist noch offen. Rot markiert einen Co-Admin. Mit Bearbeiten passt du eine vorhandene Freigabe später sicher an.",
  "security-accesses-create": "Neuen Zugang bewusst anlegen. Hier legst du einen persönlichen Zugang für eine bereits angelegte Kontaktperson an. Du entscheidest zwischen sicherem Aktivierungslink per E-Mail und einem einmaligen Zugangsblatt für den Offline-Weg. Zugangsdaten werden nicht dauerhaft offen angezeigt – das schützt das Planungsteam.",
  "security-accesses-identity": "Person eindeutig zuordnen. Wähle zuerst den passenden Ansprechpartner. Die persönliche E-Mail-Adresse dient – falls gepflegt – dem individuellen Login und Aktivierungslink. Eine eindeutige Zuordnung verhindert, dass sich mehrere Personen versehentlich einen Zugang teilen oder Änderungen nicht mehr nachvollziehbar sind.",
  "security-accesses-rights": "Die drei Rechte-Schalter richtig vergeben. Die drei Schalter heißen Aus, Lesen und Schreiben. Aus bedeutet: Der Bereich ist vollständig ausgeblendet. Lesen zeigt Inhalte ohne Änderungen. Schreiben erlaubt das Anlegen und Pflegen von Daten in diesem Bereich. Gib nur Rechte, die für die konkrete Aufgabe wirklich nötig sind – so bleiben Planung, Finanzen und sensible Informationen geschützt.",
  "security-accesses-coadmin": "Co-Admin nur gezielt vergeben. Ein Co-Admin kann im eigenen Verein nahezu alle Planungsdaten und normalen Zugänge verwalten. Er erhält aber keine Plattform- oder Masterrechte und kann keine anderen Co-Admins verwalten. Vergib diese Rolle nur an sehr vertrauenswürdige Personen, die dauerhaft die Gesamtorganisation mittragen.",
  "security-accesses-events": "Veranstaltungen bewusst freigeben. Normale Planungsteam-Zugänge sehen nur die hier angehakten Veranstaltungen. So kann eine Kontaktperson etwa beim Sommerfest helfen, ohne die Planung einer anderen Veranstaltung zu sehen. Co-Admins erhalten automatisch alle aktuellen und künftigen Veranstaltungen des Vereins.",
  "security-emergency": "Globalen Notfall-Stopp kennen. Bei einem echten Sicherheitsvorfall sperrt dieser Schalter sofort alle Planungsteam-Logins und bereits offenen Planungsteam-Sitzungen. Persönliche Vereinsadministratoren bleiben handlungsfähig. Nutze den Stopp nicht für normale Planänderungen, sondern nur bei Verdacht auf unbefugten Zugriff oder einer akuten Sicherheitslage.",
  "security-audit-logins": "Sicherheit und Logins nachvollziehen. Dieser Tab protokolliert erfolgreiche Administrator-Anmeldungen, Passwortwechsel, Einmalcode-Resets und globale Notfall-Sperren. Prüfe ihn, wenn du nachvollziehen möchtest, wann eine besonders geschützte Aktion stattgefunden hat oder ob ein Vorfall bereits bearbeitet wurde.",
  "security-audit-activity": "Änderungen und Löschungen prüfen. Im Aktivitätsverlauf siehst du, wer wann in welchem Bereich etwas erstellt, geändert oder gelöscht hat. Die Löschansicht trennt gelöschte Einträge von normalen Aktivitäten; einzelne Löschungen können – wenn möglich – gezielt wiederhergestellt werden. Jahr, Veranstaltung und Datentyp helfen beim Eingrenzen.",
  "security-audit-files": "Datei- und Import-Historie verstehen. Hier stehen erfolgreich übernommene JSON-Projektstände und – ab Pro – Excel-Module mit Zeitpunkt, Person sowie Anzahl neuer, geänderter und gelöschter Datensätze. Ein Klick auf einen Eintrag zeigt die konkreten Einzeländerungen. So prüfst du vor allem nach einem Import, was tatsächlich in die Planung übernommen wurde.",
  "security-audit-files-event-pass": "JSON-Sicherung im Event Pass verstehen. Hier siehst du erfolgreiche JSON-Sicherungen dieser Veranstaltung mit Zeitpunkt, Person sowie Anzahl neuer, geänderter und gelöschter Datensätze. Im Event Pass stehen Sicherung und Wiederherstellung ausschließlich als JSON zur Verfügung. Excel-Import und -Export beginnen ab Pro. Ein Klick auf einen Eintrag zeigt die konkreten Einzeländerungen.",
  "security-danger": "Gefahrenbereich nur als letzte Option. Dieser Bereich löscht sämtliche Planungsdaten des aktuell gewählten Jahres unwiderruflich. Andere Jahre und Passwörter bleiben erhalten. Er ist für einen vollständigen Neustart gedacht, nicht für einzelne Korrekturen. Prüfe vorher Protokolle, Filter und mögliche Wiederherstellungen.",
  "security-complete": "Sicherheit nachvollziehbar verwaltet. Du weißt jetzt, wie du Zugänge passend begrenzt, Ereignisse prüfst und geschützte Notfallfunktionen bewusst einsetzt.",
  "security-intro-event-pass": "Schutz und Protokoll im Event Pass. Hier regelst du das Administratorpasswort, prüfst Sicherheits- und Aktivitätsprotokolle und nutzt den Gefahrenbereich nur bewusst. Persönliche Planungsteam-Zugänge und deren Notfall-Stopp ergänzen das Light-Paket. Die Führung öffnet nur Ansichten und ändert nichts.",
  "security-audit-files-light": "Datei- und Import-Historie ab Pro. Im Light-Paket sind die Kernplanung, Ansprechpartner, Orte, Material und persönliche Teamzugänge verfügbar. Eine vollständige Datei-Sicherung, Excel-Import und die zugehörige Historie ergänzen das Pro-Paket. Sicherheits- und Aktivitätsprotokolle bleiben hier weiterhin nutzbar.",
  "pdf-contacts-locked": "Ansprechpartner-Übersichten ab Light. Mit Ansprechpartner-Übersichten erstellst du gegliederte Arbeitsmappen mit Bereichsverantwortung, Schichten und Checklisten. Im Event Pass ist dieser Teil gesperrt. Helfer-PDFs und gefilterte Einsatzpläne bleiben weiter nutzbar.",
  "pdf-config-locked": "PDF-Vorlage mit klaren Paketgrenzen. Titel, Zusatzspalten und Hinweise kannst du hier für die aktuelle Veranstaltung pflegen. Ein eigenes Eventlogo und automatische WhatsApp-Vorlagen stehen ab Pro bereit. Bis dahin bleibt das MyCrewMate-Logo aktiv. WhatsApp öffnet weiter einen leeren Chat für freie Nachrichten.",
  "security-accesses-locked": "Planungsteam-Zugänge ab Light. Persönliche Planungsteam-Zugänge verwalten Fachrechte und Veranstaltungsfreigaben für einzelne Personen. Im Event Pass bleibt die Planung sicher beim Hauptadministrator. Mit Light kommen bis zu fünf persönliche Zugänge hinzu. Die übrigen Sicherheits- und Protokollbereiche bleiben weiter verfügbar.",
  "security-accesses-filter-locked": "Zugangsfilter ab Light. Dieser Filter gehört zu persönlichen Planungsteam-Zugängen und steht deshalb ab Light bereit. Dort findest du Teammitglieder gezielt nach Jahr oder Veranstaltung. Im Event Pass gibt es nur den Hauptadministrator für die eine Veranstaltung, daher ist keine Zugangsliste zu filtern.",
  "security-accesses-list-locked": "Zugangskarten ab Light. Statuskarten für weitere Teammitglieder gibt es ab Light. Dort erkennst du eingerichtete Passwörter, Rollen und Freigaben pro Person. Im Event Pass bleibt die Verwaltung bewusst schlank: Der Hauptadministrator verantwortet die einzige Veranstaltung direkt.",
  "security-accesses-create-locked": "Neue Teamzugänge ab Light. Eigene Anmeldungen für weitere Personen, Aktivierungslinks und Zugangsblätter stehen ab Light bereit. Das ist sinnvoll, wenn Ansprechpartner oder Einsatzplaner mit eigenen Rechten arbeiten sollen. Im Event Pass bleibt die Planung beim Hauptadministrator.",
  "security-accesses-identity-locked": "Persönliche Anmeldung ab Light. Die Zuordnung eines eigenen Logins zu einem Ansprechpartner ist Teil der persönlichen Teamzugänge ab Light. Sie sorgt dafür, dass Änderungen einer Person zugeordnet bleiben. Im Event Pass ist kein weiterer Login vorgesehen; der Hauptadministrator bleibt die feste Ansprechperson.",
  "security-accesses-rights-locked": "Fachbereichsrechte ab Light. Die Schalter Aus, Lesen und Schreiben verteilen Rechte an weitere Teammitglieder und stehen ab Light bereit. Im Event Pass gibt es keine zusätzlichen Planungsteam-Zugänge, deshalb müssen dort keine Fachbereichsrechte vergeben werden.",
  "security-accesses-coadmin-locked": "Co-Admins ab Light. Einen weiteren Co-Admin oder Planungszugang kannst du ab Light einrichten. Light enthält bis zu fünf persönliche Teamzugänge, Pro bis zu vierzehn. Im Event Pass bleibt die Gesamtverantwortung beim Hauptadministrator.",
  "security-accesses-events-locked": "Eventfreigaben ab Light. Veranstaltungen für einzelne Teammitglieder freizugeben, ist Teil der persönlichen Zugänge ab Light. Im Event Pass ist genau eine Veranstaltung enthalten und sie wird vom Hauptadministrator vollständig betreut. Deshalb gibt es hier keine separate Auswahl.",

  "help-intro": "Im Hilfe-Center schnell zurechtfinden. Hier findest du kurze Anleitungen für die gesamte Planung – von der ersten Orientierung bis zu PDFs, Rechten und Sicherungen.",
  "help-search": "Direkt nach einem Begriff suchen. Tippe einfach ein Stichwort wie Helfer, Einsatzplan, Material, PDF oder Passwort ein. Die sichtbaren Kapitel passen sich sofort an.",
  "help-filters": "Hilfe nach Rolle filtern. Mit den Rollenfiltern blendest du Inhalte für alle, für das Planungsteam oder für Administratoren ein. So bleibt die Anleitung passend zu deinen Rechten.",
  "help-chapters": "Kapitel öffnen und direkt weiterarbeiten. Öffne das passende Kapitel, lies die kompakten Schritte und nutze die Links direkt zum jeweiligen Arbeitsbereich. Klemmi bleibt auch dort wieder für dich erreichbar.",
  "help-complete": "Geschafft! Jetzt weißt du, wie du in der Hilfe schnell zur passenden Antwort und direkt weiter zur Arbeit kommst.",

  "plan-intro": "Ich zeige dir den Einsatzplan von Anfang bis Ende. Gibt es schon Schichten, erklären wir sie direkt. Ist die Planung noch leer, legen wir gemeinsam eine erste Übungsschicht an. So siehst du alles an echten Daten.",
  "plan-empty": "Hier ist noch keine Schicht angelegt. Lass uns gerade gemeinsam eine Übungsschicht anlegen. Du bestimmst, ob sie später eine echte Schicht bleibt oder ob du sie wieder löscht.",
  "plan-basics": "Tag und Personalbedarf festlegen. Wähle den passenden Eventtag und die Zahl der benötigten Helferplätze. So wird Unterbesetzung später sofort sichtbar.",
  "plan-task": "Bereich und Aufgabe benennen. Ein klarer Bereich und eine konkrete Aufgabe helfen dem Team, die Schicht in der Liste und auf dem Gelände sofort einzuordnen.",
  "plan-location-event-pass": "Ort für die Schicht einordnen. Bei dieser Schicht kannst du einen Ort als klare Einordnung ergänzen. Im Event Pass bleibt die Planung bewusst schlank. Eine zentrale Ortsverwaltung und die Kartenansicht sind nicht enthalten.",
  "plan-location-light": "Zentral gepflegten Ort auswählen. Wähle hier einen zentral gepflegten Ort aus. Im Light-Paket steht er in Schichten, Vorbereitung und Material immer wieder zur Auswahl. GPS-Punkte, Strecken und die Live-Standortkarte sind eine Erweiterung ab Pro.",
  "plan-location-pro": "Ort mit Karte verknüpfen. Wähle hier einen zentral gepflegten Ort aus. In Pro und Enterprise kann derselbe Ort zusätzlich mit GPS-Daten und der Live-Standortkarte verknüpft werden. So sieht das Team die Aufgabe im Plan und bei Bedarf direkt auf der Karte.",
  "plan-time-window": "Beginn und Ende festlegen. Hier legst du fest, wann die Schicht beginnt und endet. Trage beide Uhrzeiten ein, wenn die Aufgabe zu einem festen Zeitraum besetzt werden muss. Für eine ganztägige Schicht lässt du beide Felder einfach leer. So kann das Team die Helfer später passend zu ihren verfügbaren Zeiten einteilen.",
  "plan-time": "Flexible Belegung aktivieren. Mit der flexiblen Belegung machst du deine Schicht super flexibel! Beispiel: Deine Schicht geht von 8 Uhr bis 12 Uhr, aber ein Helfer kann nur von 9 Uhr bis 10 Uhr? Kein Problem! Ist das Häkchen gesetzt, kannst du den Helfer trotzdem zuweisen. Im Einsatzplan wird die Schicht dann als knapp besetzt markiert. So siehst du auf einen Blick, dass noch nicht die gesamte Schichtzeit abgedeckt ist und noch weitere Helfer fehlen!",
  "plan-save": "Schicht speichern. Erst der markierte Speichern-Button legt eine Schicht wirklich an. Für diese Erklärung klickst du nicht darauf. Ich zeige dir jetzt direkt, wie die fertige Planung anschließend aussieht.",
  "plan-practice-save": "Trag für die Übung einfach Tag, Bereich, Aufgabe und Bedarf ein. Mit Speichern legst du die Schicht wirklich an. Danach erkläre ich sie direkt an deiner eigenen Kachel.",
  "plan-overview": "Schichtkachel und Bedarf lesen. Jede Schicht erscheint als eigene Kachel. Oben stehen Tag, Bereich und Aufgabe. Der Balken darunter zeigt sofort, wie viele Plätze bereits besetzt sind. Bei einer leeren Planung sieht die erste angelegte Schicht genau so aus.",
  "plan-practice-cleanup": "Super, jetzt siehst du deine erste Schicht. Wenn sie nur zum Üben war, kannst du sie später mit dem roten Löschen-Symbol wieder entfernen. Wenn sie schon passt, bleibt sie einfach stehen.",
  "plan-coverage": "Offene Plätze sofort erkennen. Die Anzeige zum Personalbedarf sagt zum Beispiel zwei von vier Helfern. Erst wenn die erforderliche Zahl erreicht ist, gilt die Schicht als vollständig besetzt. Darum lohnt sich der Blick auf den Balken bei jeder Änderung.",
  "plan-candidates": "Passende Helfer auswählen. Rechts in der Kachel stehen nur Helfer, die für die Schicht grundsätzlich in Frage kommen. Die Kästchen vorne dienen der Mehrfachauswahl. So füllst du mehrere freie Plätze in einem Schritt statt jede Person einzeln anzulegen.",
  "plan-signals": "Tageszeichen, Zeitfenster und Begleitung lesen. Die orange Umrandung zeigt dir genau die Helferliste. Falls vor einem Namen eine Uhr steht, kann die Person nur in einem bestimmten Zeitfenster helfen. Fahre mit der Maus über Uhr oder Namen, dann siehst du die genauen Zeiten. Ein Familiensymbol bedeutet eine zusätzliche Begleitung. Auch deren Hinweis siehst du beim Darüberfahren. Über dem Namen erscheinen außerdem Hinweise für die persönliche PDF. Die Tagesfarben zeigen: Grün ist frei, Gelb schon eingeteilt, Rot nicht verfügbar. Neu heißt noch in keiner Schicht eingeteilt.",
  "plan-assign": "Passende Helfer gesammelt zuordnen. Setze vorne bei allen passenden Personen ein Häkchen und übernimm die Auswahl gesammelt. Mit Maus über Name, Uhr oder Familiensymbol siehst du Zeitfenster, Begleitung und PDF-Hinweise sofort. Auf dem Smartphone öffnest du die Details über den Namen. Danach kontrollierst du erneut den Besetzungsbalken.",
  "plan-filters": "Viele Schichten schnell eingrenzen. Mit Meine Aufgaben, Tagen, Bereichen, Status und Warnungen reduzierst du die Ansicht auf genau den Teil des Plans, den du gerade prüfen willst. So bleiben auch mehrtägige Veranstaltungen übersichtlich.",
  "plan-search": "Nach Aufgabe, Bereich oder Helfer suchen. Die Suche findet sofort passende Schichten und Namen. Das hilft zum Beispiel bei einer Rückfrage eines Helfers, wenn du nur seinen Namen oder einen Bereich kennst.",
  "plan-view": "Liste oder Kacheln passend zur Aufgabe wählen. Die Kachelansicht eignet sich besonders zum Besetzen, weil Helferlisten und Bedarf direkt nebeneinander stehen. Die Liste ist ideal für einen schnellen Gesamtüberblick. Beide Ansichten zeigen dieselben Planungsdaten.",
  "plan-complete": "Einsatzplan im Griff! Du kennst jetzt den Ablauf. Schichten sauber anlegen, Bedarf erkennen, passende Helfer anhand ihrer Verfügbarkeit auswählen, die Besetzung prüfen und anschließend die Zusagen zuverlässig nachhalten.",

  "preparation-intro": "Vorbereitungsaufgaben sicher planen. Ich zeige dir die echte Aufgabenanlage: Aufgabe formulieren, Zuständigkeit und Termin festlegen und den ersten Stand sauber festhalten.",
  "preparation-area-location-event-pass": "Bereich und Ort zuerst einordnen. Ordne die Vorbereitungsaufgabe zuerst einem Bereich und bei Bedarf einem Ort zu. Die Ortsangabe sorgt für Klarheit in der Aufgabe. Eine zentrale Ortsverwaltung und Karte sind im Event Pass nicht enthalten.",
  "preparation-area-location-light": "Bereich und zentralen Ort wählen. Ordne die Vorbereitungsaufgabe zuerst einem Bereich und einem zentral gepflegten Ort zu. Der Ort kann später auch in Schichten und im Material verwendet werden. GPS-Punkte und die Live-Standortkarte gehören ab Pro dazu.",
  "preparation-area-location-pro": "Bereich, Ort und Karte einordnen. Ordne die Vorbereitungsaufgabe zuerst einem Bereich und einem zentral gepflegten Ort zu. In Pro und Enterprise kann derselbe Ort zusätzlich GPS-Daten und einen Platz auf der Live-Standortkarte erhalten.",
  "preparation-task": "Aufgabe klar formulieren. Beschreibe konkret, was erledigt werden soll. Bereich und Ort helfen, die Aufgabe später schnell wiederzufinden.",
  "preparation-details": "Verantwortung und Frist zuordnen. Wähle bei Bedarf eine verantwortliche Person und einen Termin. Beides kann später jederzeit angepasst werden.",
  "preparation-logbook": "Ersten Stand notieren. Im Logbuch gehören wichtige Hinweise, Absprachen und nächste Schritte. Der Eintrag bleibt nachvollziehbar gespeichert.",
  "preparation-save": "Aufgabe speichern. Klicke auf den markierten Speichern-Button. Erst dein Klick legt die Vorbereitungsaufgabe an.",
  "preparation-complete": "Vorbereitungsaufgabe angelegt! Die Aufgabe steht jetzt in der Vorbereitung. Zuständige, Frist und Logbuch kannst du jederzeit weiterführen.",

  "postprocessing-intro": "Nachbereitung verbindlich festhalten. Ich zeige dir die echte Nachbereitungsanlage: Aufgabe benennen, Verantwortliche und Termin einordnen und Übergaben dokumentieren.",
  "postprocessing-area-location-event-pass": "Bereich und Ort zuerst einordnen. Ordne die Nachbereitungsaufgabe zuerst einem Bereich und bei Bedarf einem Ort zu. Die Ortsangabe sorgt für Klarheit in der Aufgabe. Eine zentrale Ortsverwaltung und Karte sind im Event Pass nicht enthalten.",
  "postprocessing-area-location-light": "Bereich und zentralen Ort wählen. Ordne die Nachbereitungsaufgabe zuerst einem Bereich und einem zentral gepflegten Ort zu. Der Ort kann später auch in Schichten, Vorbereitung und Material verwendet werden. GPS-Punkte und die Live-Standortkarte gehören ab Pro dazu.",
  "postprocessing-area-location-pro": "Bereich, Ort und Karte einordnen. Ordne die Nachbereitungsaufgabe zuerst einem Bereich und einem zentral gepflegten Ort zu. In Pro und Enterprise kann derselbe Ort zusätzlich GPS-Daten und einen Platz auf der Live-Standortkarte erhalten.",
  "postprocessing-task": "Aufgabe konkret benennen. Schreibe kurz und eindeutig, was nach dem Event erledigt werden muss – zum Beispiel Rückgabe, Abbau oder Abrechnung.",
  "postprocessing-details": "Verantwortung und Termin setzen. Ordne die Aufgabe bei Bedarf einer Person zu und lege eine Frist fest. Beides darf später angepasst werden.",
  "postprocessing-logbook": "Übergabe und Hinweise dokumentieren. Im Logbuch kommen wichtige Hinweise, Ergebnisse und nächste Schritte. So bleibt der Abschluss nachvollziehbar.",
  "postprocessing-save": "Aufgabe speichern. Klicke auf den markierten Speichern-Button. Erst dein Klick legt die Nachbereitungsaufgabe an.",
  "postprocessing-complete": "Nachbereitungsaufgabe angelegt! Die Aufgabe steht jetzt in der Nachbereitung. So bleiben Abbau, Rückgaben und offene Punkte für das Team sichtbar.",

  "materials-intro": "Material schnell und sauber erfassen. Ich zeige dir die echte Materialanlage: Artikel benennen, Menge eintragen und Beschaffung oder Einsatzort eindeutig festhalten.",
  "materials-name": "Artikel klar benennen. Trage zuerst ein, was benötigt wird – zum Beispiel Bierzeltgarnitur, Kabeltrommel oder Kaffeebecher.",
  "materials-details": "Menge und Einordnung festhalten. Menge, Einheit und Kategorie machen den Bedarf nachvollziehbar. Ort und Beschaffungsstand kannst du bei Bedarf direkt ergänzen.",
  "materials-save": "Materialposition speichern. Klicke auf den markierten Speichern-Button. Erst dein Klick legt den Artikel tatsächlich im Materialplan an.",
  "materials-complete": "Materialposition angelegt! Der Artikel ist jetzt im Materialplan. Status, Verantwortliche und Ort kannst du später jederzeit ergänzen oder anpassen.",

  "locations-intro": "Orte und Standorte sauber anlegen. Ich zeige dir die echte Standortanlage: Namen vergeben, Koordinaten eintragen und den Ort anschließend in Schichten, Material und Vorbereitung verwenden.",
  "locations-name": "Ort eindeutig benennen. Gib dem Standort einen Namen, den das Team auf Anhieb versteht – zum Beispiel VP acht, Pumptrack oder Kuchenstand.",
  "locations-coordinates": "Position auf der Karte festlegen. Breiten- und Längengrad positionieren den Standort auf der Live-Karte. Ein Marker-Logo darunter ist optional.",
  "locations-light": "Orte ohne Karte nutzen. Im Light-Paket verwaltest du hier zentrale Einsatzorte für Schichten, Vorbereitung und Material. Koordinaten, Strecken und die Live-Standortkarte kommen ab Pro dazu.",
  "locations-save": "Standort speichern. Klicke auf den markierten Button. Erst dein Klick legt den Standort wirklich an.",
  "locations-complete": "Standort angelegt! Der Ort steht jetzt in Schichten, Vorbereitung und Material zur Auswahl und erscheint auf der Live-Standortkarte.",
} as const;

export type KlemmiAudioId = keyof typeof KLEMMI_AUDIO_SCRIPTS;

/**
 * Jede Tourreferenz gehört verbindlich zur vorproduzierten Klemmi-Stimme.
 * Dies ist zugleich die maschinenlesbare Auditquelle für alle Tutorialschritte:
 * keine Browser-Systemstimme und keine zweite Sprecherstimme werden verwendet.
 */
export const KLEMMI_AUDIO_VOICE_MANIFEST: Readonly<
  Record<KlemmiAudioId, { voice: typeof KLEMMI_VOICE_PROFILE.voice }>
> = Object.freeze(
  Object.fromEntries(
    (Object.keys(KLEMMI_AUDIO_SCRIPTS) as KlemmiAudioId[]).map(id => [
      id,
      { voice: KLEMMI_VOICE_PROFILE.voice },
    ])
  ) as Record<KlemmiAudioId, { voice: typeof KLEMMI_VOICE_PROFILE.voice }>
);

/**
 * Beim bewussten Öffnen einer Klemmi-Tour wählt der Browser genau einen dieser
 * kurzen Einstiege. Der letzte Clip wird ausgeschlossen, damit sich kein
 * Einstieg unmittelbar wiederholt.
 */
export const KLEMMI_OPENING_AUDIO_IDS = [
  "opening-clears-throat",
  "opening-cough",
  "opening-sniff",
  "opening-ach-herrje",
  "opening-servus",
  "opening-gruess-gott",
  "opening-hallo",
  "opening-na-dann",
  "opening-auf-gehts",
  "opening-moin",
  "opening-halloechen",
  "opening-tadaa",
  "opening-na-schau-an",
  "opening-guten-tag",
  "opening-klingeling",
  "opening-hmm",
  "opening-jawohl",
  "opening-aha",
  "opening-hey-ho",
  "opening-na-endlich",
  "opening-hoi",
  "opening-bitte-sehr",
  "opening-wir-packen-das",
  "opening-einen-moment",
  "opening-hopp-hopp",
  "opening-zack",
  "opening-lass-uns-schauen",
  "opening-alles-klar",
  "opening-ganz-entspannt",
  "opening-wunderbar",
] as const satisfies readonly KlemmiAudioId[];

/**
 * Neue Sprachfassungen erhalten eine eigene URL. Dadurch kann kein Browser
 * trotz langer Cache-Zeit versehentlich eine vorherige Klemmi-Aufnahme spielen.
 */
const KLEMMI_AUDIO_REVISIONS: Partial<Record<KlemmiAudioId, string>> = {
  "package-tip-event-pass": "20261001-package-comparison-v1",
  "package-tip-light": "20261001-package-comparison-v1",
  "package-tip-pro": "20261001-package-comparison-v1",
  "dashboard-map-locked": "20260930-achird-audit-v2",
  "dashboard-map-locked-light": "20260930-achird-audit-v1",
  "dashboard-helpers-active-no-donations": "20260930-achird-audit-v1",
  "dashboard-helpers-empty-no-donations": "20260930-achird-audit-v1",
  "pdf-intro-event-pass": "20260930-achird-audit-v1",
  "pdf-plan-event-pass": "20260930-achird-audit-v1",
  "pdf-contacts-locked": "20260930-achird-audit-v2",
  "pdf-config-light": "20260930-achird-audit-v1",
  "pdf-plan": "20260930-achird-audit-v2",
  "pdf-config": "20260930-achird-audit-v2",
  "security-intro-event-pass": "20260930-achird-audit-v1",
  "security-accesses-overview": "20260930-achird-audit-v2",
  "security-accesses-list": "20260930-achird-audit-v2",
  "security-emergency": "20260930-achird-audit-v2",
  "security-audit-files": "20260930-achird-audit-v3",
  "security-audit-files-light": "20260930-achird-audit-v1",
  "helpers-overview": "20260928-helper-overview-v1",
  "helpers-person": "20260928-informational-tour-v1",
  "helpers-contact": "20260928-informational-tour-v1",
  "helpers-contact-event-pass": "20260930-helper-package-gates-v1",
  "helpers-details": "20260928-informational-tour-v1",
  "helpers-availability-entry": "20260928-create-availability-v1",
  "helpers-donation": "20260928-informational-tour-v1",
  "helpers-donation-locked": "20260930-helper-package-gates-v1",
  "helpers-save": "20260928-informational-tour-v1",
  "helpers-save-locked": "20260930-helper-package-gates-v1",
  "helpers-availability": "20260928-create-availability-v1",
  "helpers-plan-fill": "20260928-informational-tour-v1",
  "helpers-feedback": "20260928-informational-tour-v1",
  "helpers-action-donation": "20260928-informational-tour-v1",
  "helpers-action-donation-locked": "20260930-helper-package-gates-v1",
  "helpers-action-whatsapp": "20260928-informational-tour-v1",
  "helpers-action-whatsapp-locked": "20260930-helper-package-gates-v1",
  "helpers-action-pdf": "20260928-informational-tour-v1",
  "helpers-action-edit": "20260928-informational-tour-v1",
  "helpers-action-delete": "20260928-informational-tour-v1",
  "helpers-complete": "20260928-informational-tour-v1",
  "first-login-intro": "20260927-joke-v2",
  "first-login-co-admin": "20260927-joke-v2",
  "login-warmgelaufen": "20260927-daily-greetings-v1",
  "login-chaos": "20260927-daily-greetings-v1",
  "login-ehrenamt": "20260927-daily-greetings-v1",
  "login-aermel": "20260927-daily-greetings-v1",
  "login-kaffee": "20260927-daily-greetings-v1",
  "login-tabellen": "20260927-daily-greetings-v1",
  "login-druecker": "20260927-daily-greetings-v1",
  "login-noch-eins": "20260927-daily-greetings-v1",
  "login-datenbank": "20260927-daily-greetings-v1",
  "login-system": "20260927-daily-greetings-v1",
  "login-superhelden": "20260927-daily-greetings-v1",
  "login-roter-teppich": "20260927-daily-greetings-v1",
  "idle-vorstehhund": "20260927-daily-greetings-v1",
  "idle-kaffee": "20260927-daily-greetings-v1",
  "idle-standbild": "20260927-daily-greetings-v1",
  "idle-wuerstchenbude": "20260927-daily-greetings-v1",
  "idle-singen": "20260927-daily-greetings-v1",
  "error-halt-stopp": "20260927-daily-greetings-v1",
  "error-fast-perfekt": "20260927-daily-greetings-v1",
  "error-zauberei": "20260927-daily-greetings-v1",
  "error-rotes-feld": "20260927-daily-greetings-v1",
  "error-verrats-keinem": "20260927-daily-greetings-v1",
  "error-kleingedrucktes": "20260927-daily-greetings-v1",
  "error-knapp-vorbei": "20260927-daily-greetings-v1",
  "error-schranke": "20260927-daily-greetings-v1",
  "success-zack": "20260927-daily-greetings-v1",
  "success-boom": "20260927-daily-greetings-v1",
  "success-volltreffer": "20260927-daily-greetings-v1",
  "success-reibungslos": "20260927-daily-greetings-v1",
  "success-baem": "20260927-daily-greetings-v1",
  "success-leerstand": "20260927-daily-greetings-v1",
  "success-bilderbuch": "20260927-daily-greetings-v1",
  "success-bingo": "20260927-daily-greetings-v1",
  "success-high-five": "20260927-daily-greetings-v1",
  "success-passt": "20260927-daily-greetings-v1",
  "success-geschmiert": "20260927-daily-greetings-v1",
  "success-arbeitslos": "20260927-daily-greetings-v1",
  "dashboard-intro": "20260927-dashboard-tour-v1",
  "dashboard-complete": "20260927-dashboard-tour-v1",
  "dashboard-details-active-stacked": "20260928-dashboard-stacked-layout-v1",
  "dashboard-details-empty-stacked": "20260928-dashboard-stacked-layout-v1",
  "donations-intro": "20260928-information-tour-v1",
  "donations-save": "20260928-information-tour-v1",
  "donations-overview": "20260928-information-tour-v1",
  "donations-filters": "20260928-information-tour-v1",
  "donations-outputs": "20260928-information-tour-v1",
  "donations-complete": "20260928-information-tour-v1",
  "plan-intro": "20260928-empty-plan-tour-v2",
  "plan-empty": "20260928-empty-plan-tour-v1",
  "plan-basics": "20260928-information-tour-v1",
  "plan-task": "20260928-information-tour-v1",
  "plan-location-event-pass": "20260930-package-location-tour-v1",
  "plan-location-light": "20260930-package-location-tour-v1",
  "plan-location-pro": "20260930-package-location-tour-v1",
  "locations-light": "20260930-light-locations-audio-v1",
  "plan-time-window": "20260930-time-window-v1",
  "plan-time": "20260930-flexible-assignment-v1",
  "plan-save": "20260928-information-tour-v1",
  "plan-practice-save": "20260928-empty-plan-tour-v1",
  "plan-overview": "20260928-male-voice-v2",
  "plan-practice-cleanup": "20260928-empty-plan-tour-v1",
  "plan-coverage": "20260928-information-tour-v1",
  "plan-candidates": "20260928-information-tour-v1",
  "plan-signals": "20260928-plan-tooltip-v3",
  "plan-assign": "20260928-plan-tooltip-v3",
  "plan-filters": "20260928-information-tour-v1",
  "finances-save": "20260928-adaptive-area-tour-v1",
  "marketing-intro": "20260928-adaptive-area-tour-v1",
  "marketing-name": "20260928-adaptive-area-tour-v1",
  "marketing-details": "20260928-adaptive-area-tour-v1",
  "marketing-save": "20260928-adaptive-area-tour-v1",
  "marketing-complete": "20260928-adaptive-area-tour-v1",
  "approvals-intro": "20260928-adaptive-area-tour-v1",
  "approvals-name": "20260928-adaptive-area-tour-v1",
  "approvals-save": "20260928-adaptive-area-tour-v1",
  "approvals-complete": "20260928-adaptive-area-tour-v1",
  "preparation-area-location-event-pass": "20260930-package-location-tour-v1",
  "preparation-area-location-light": "20260930-package-location-tour-v1",
  "preparation-area-location-pro": "20260930-package-location-tour-v1",
  "preparation-overview-save": "20260928-adaptive-area-tour-v1",
  "preparation-overview": "20260928-adaptive-area-tour-v1",
  "postprocessing-area-location-event-pass": "20260930-package-location-tour-v1",
  "postprocessing-area-location-light": "20260930-package-location-tour-v1",
  "postprocessing-area-location-pro": "20260930-package-location-tour-v1",
  "postprocessing-overview-save": "20260928-adaptive-area-tour-v1",
  "postprocessing-overview": "20260928-adaptive-area-tour-v1",
  "materials-overview-save": "20260928-adaptive-area-tour-v1",
  "materials-overview": "20260928-adaptive-area-tour-v1",
  "marketing-overview-save": "20260928-adaptive-area-tour-v1",
  "marketing-overview": "20260928-adaptive-area-tour-v1",
  "approvals-overview-save": "20260928-adaptive-area-tour-v1",
  "approvals-overview": "20260928-adaptive-area-tour-v1",
  "locations-overview-save": "20260928-adaptive-area-tour-v1",
  "locations-overview": "20260928-adaptive-area-tour-v1",
  "contacts-overview-save": "20260928-adaptive-area-tour-v1",
  "contacts-overview": "20260928-adaptive-area-tour-v1",
  "donations-overview-save": "20260928-adaptive-area-tour-v1",
  "donations-overview-summary": "20260928-adaptive-area-tour-v1",
  "finances-overview-save": "20260928-adaptive-area-tour-v1",
  "finances-overview": "20260928-adaptive-area-tour-v1",
  "plan-search": "20260928-information-tour-v1",
  "plan-view": "20260928-information-tour-v1",
  "plan-complete": "20260928-information-tour-v1",
  "security-intro": "20260929-security-admin-detail-v1",
  "security-password": "20260929-security-admin-detail-v2",
  "security-accesses-filter": "20260929-security-admin-detail-v1",
  "security-accesses-create": "20260929-security-admin-detail-v1",
  "security-accesses-identity": "20260929-security-admin-detail-v1",
  "security-accesses-rights": "20260929-security-admin-detail-v2",
  "security-accesses-coadmin": "20260929-security-admin-detail-v1",
  "security-accesses-events": "20260929-security-admin-detail-v1",
  "security-audit-logins": "20260929-security-admin-detail-v1",
  "security-audit-activity": "20260929-security-admin-detail-v1",
  "security-audit-files-event-pass": "20260930-event-pass-json-v1",
  "security-danger": "20260929-security-admin-detail-v2",
  "security-complete": "20260929-security-admin-detail-v1",
  "pdf-config-locked": "20260930-package-context-v1",
  "security-accesses-locked": "20260930-package-context-v1",
  "security-accesses-filter-locked": "20260930-security-package-steps-v1",
  "security-accesses-list-locked": "20260930-security-package-steps-v1",
  "security-accesses-create-locked": "20260930-security-package-steps-v1",
  "security-accesses-identity-locked": "20260930-security-package-steps-v1",
  "security-accesses-rights-locked": "20260930-security-package-steps-v1",
  "security-accesses-coadmin-locked": "20260930-security-package-steps-v1",
  "security-accesses-events-locked": "20260930-security-package-steps-v1",
};

export function isKlemmiAudioId(value: string): value is KlemmiAudioId {
  return value in KLEMMI_AUDIO_SCRIPTS;
}

export function klemmiAudioUrl(id: KlemmiAudioId) {
  const revision = KLEMMI_AUDIO_REVISIONS[id];
  return revision ? `${KLEMMI_AUDIO_ROUTE}/${id}?v=${revision}` : `${KLEMMI_AUDIO_ROUTE}/${id}`;
}
