export const KLEMMI_AUDIO_ROUTE = "/api/klemmi/audio";

/** Einheitliche Markenstimme für alle bestehenden und zukünftigen Klemmi-Touren. */
export const KLEMMI_VOICE_PROFILE = {
  voice: "Achird",
  label: "Klemmi – warm und organisatorisch",
  description:
    "Freundliche männliche Cartoon-Stimme: warm, klar, leicht verspielt und strukturiert.",
} as const;

/**
 * Feste, vorproduzierte Klemmi-Texte. Die Dateien liegen ausschließlich im
 * Produkt-Container und werden erst ausgeliefert, wenn eine Tour bewusst
 * geöffnet wurde. Es werden keine Eingaben oder personenbezogenen Daten an
 * einen Sprachdienst übertragen.
 */
export const KLEMMI_AUDIO_SCRIPTS = {
  "opening-clears-throat": "[clears throat] So, los geht's!",
  "opening-cough": "[cough] Hups, kurz sortiert. Jetzt aber!",
  "opening-sniff": "[sniffs] Alles klar, ich bin bereit!",
  "opening-ach-herrje": "Ach herrje, da bin ich ja!",
  "opening-servus": "Servus, Klemmi ist da!",
  "opening-gruess-gott": "Grüß Gott, schauen wir gemeinsam drauf!",
  "opening-hallo": "Hallo, ich helfe dir gern!",
  "opening-na-dann": "Na dann, legen wir los!",
  "opening-auf-gehts": "Auf geht's, ich bin dabei!",
  "opening-moin": "Moin, Klemmi ist startklar!",
  "opening-halloechen": "Hallöchen, schön, dass du da bist!",
  "opening-tadaa": "Tadaa, dein Klemmi ist da!",
  "opening-na-schau-an": "Na, schau an, dann gucken wir mal!",
  "opening-guten-tag": "Guten Tag, worum kümmern wir uns?",
  "opening-klingeling": "Klingeling, Klemmi meldet sich!",
  "opening-hmm": "Hmm, schauen wir mal.",
  "opening-jawohl": "Jawohl, ich bin zur Stelle!",
  "opening-aha": "Aha, das kriegen wir hin!",
  "opening-hey-ho": "Hey ho, Klemmi übernimmt!",
  "opening-na-endlich": "Na endlich, los geht's!",
  "opening-hoi": "Hoi, ich bin schon da!",
  "opening-bitte-sehr": "Bitte sehr, deine Hilfe ist da!",
  "opening-wir-packen-das": "Keine Sorge, wir packen das!",
  "opening-einen-moment": "Einen kleinen Moment, ich bin ganz Ohr!",
  "opening-hopp-hopp": "Hopp hopp, schauen wir rein!",
  "opening-zack": "Zack, Klemmi ist bereit!",
  "opening-lass-uns-schauen": "Lass uns gemeinsam schauen!",
  "opening-alles-klar": "Alles klar, ich zeig's dir!",
  "opening-ganz-entspannt": "Ganz entspannt, wir gehen das zusammen an!",
  "opening-wunderbar": "Wunderbar, dann starten wir!",

  "first-login-intro": "Hallo! Ich bin Klemmi. Und nein – nicht weil ich verklemmt bin. [laughing] Sondern weil ich immer genau dann zur Stelle bin, wenn es irgendwo klemmt, oder halt, wenn du das erste Mal hier bist! Egal ob Schichten, Helfer oder Event-Planung: Wenn du mal nicht weiterweißt, klick mich einfach an! Du findest mich ab jetzt auf jeder Seite ganz oben im Menü.",
  "first-login-co-admin": "Hallo! Ich bin Klemmi. Und nein – nicht weil ich verklemmt bin. [laughing] Sondern weil ich immer genau dann zur Stelle bin, wenn es irgendwo klemmt, oder halt, wenn du das erste Mal hier bist! Egal ob Schichten, Helfer oder Event-Planung: Wenn du mal nicht weiterweißt, klick mich einfach an! Du findest mich ab jetzt auf jeder Seite ganz oben im Menü. Und noch ein Tipp für dich als Co-Admin: Im nächsten Schritt siehst du deine wichtigsten Rechte. Die vollständige Rechte-Matrix findest du später jederzeit im Hilfe-Bereich.",
  "login-warmgelaufen": "Da bist du ja wieder! Ich hab die Tabellen schon mal warmgelaufen. Wo legen wir los?",
  "login-chaos": "Servus! Bereit, das Chaos in geordnete Bahnen zu lenken? Ich wär's jedenfalls!",
  "login-ehrenamt": "Eingeloggt und startklar! Lass uns das Ehrenamt mal wieder ein bisschen einfacher machen.",
  "login-aermel": "Hey! Schön, dass du da bist. Ich hab schon mal die Ärmel hochgekrempelt – wenn ich welche hätte!",
  "login-kaffee": "Kaffee steht bereit, System ist hochgefahren. Dann zeig mal, was für ein Event-Genie in dir steckt!",
  "login-tabellen": "Zurück am Drücker! Lass uns ein paar Aufgaben wegzaubern – ganz ohne Magie, nur mit System!",
  "login-druecker": "Zurück am Drücker! Welche Aufgabe knacken wir heute zuerst?",
  "login-noch-eins": "Endlich Verstärkung! Ich dachte schon, ich muss die Schichten ganz alleine rocken.",
  "login-datenbank": "Na, wer klopft denn da an die Datenbank? Lass uns ein paar Haken auf die To-do-Liste setzen!",
  "login-system": "Welcome back! Das System läuft geschmeidig, der Klemmi ist wach. Wo packen wir als Erstes an?",
  "login-superhelden": "Wer braucht schon Superhelden, wenn wir deinen Login-Button haben? Welchen Plan retten wir heute?",
  "login-roter-teppich": "Da ist ja der Star des Vereins! Ich hab den roten Teppich im Dashboard schon ausgerollt.",

  "idle-vorstehhund": "Ich stehe bereit wie ein Vorstehhund. Sag mir einfach, wo ich hinspringen soll!",
  "idle-kaffee": "Mein virtueller Kaffee wird kalt. Sollen wir weitermachen?",
  "idle-standbild": "Standbild oder Denkpause? Ich warte geduldig, aber nicht zu geschniegelt.",
  "idle-wuerstchenbude": "In der Zeit, die du überlegst, hätte ich fast eine Würstchenbude organisiert!",
  "idle-singen": "Wenn hier gar nichts passiert, fange ich an zu singen. Das willst du nicht.",

  "error-halt-stopp": "Halt, stopp, fast perfekt. Da fehlt noch was.",
  "error-fast-perfekt": "Fast perfekt! Ein kleines Feld fehlt noch, dann bist du durch.",
  "error-zauberei": "Das Feld füllt sich leider nicht mit Zauberei. Hilfst du kurz nach?",
  "error-rotes-feld": "Das rote Feld winkt schon. Einmal kurz ergänzen, bitte.",
  "error-verrats-keinem": "Ich verrat's keinem, aber dieses Feld braucht noch Inhalt.",
  "error-kleingedrucktes": "Wer liest schon Kleingedrucktes? Ich. Und da fehlt noch eine Kleinigkeit.",
  "error-knapp-vorbei": "Netter Schuss, aber knapp am Ziel vorbei. Schau noch mal auf das markierte Feld.",
  "error-schranke": "So lassen wir dich nicht durch die Schranke. Eine Angabe fehlt noch, Meister!",

  "success-zack": "Zack! Wieder eine Schicht eingetütet.",
  "success-boom": "Boom! Schicht steht. Stark gemacht!",
  "success-volltreffer": "Volltreffer! Die Lücke im Plan ist Geschichte.",
  "success-reibungslos": "Reibungslos eingeteilt. So macht Planung Laune!",
  "success-baem": "Bäm! Besser hätte das kein Profi-Disponent gemacht.",
  "success-leerstand": "Tschüss Leerstand, hallo Helfer!",
  "success-bilderbuch": "Eine Schicht wie aus dem Bilderbuch.",
  "success-bingo": "Bingo! Wieder ein Helfer glücklich untergebracht.",
  "success-high-five": "High Five! Die Schicht ist bombensicher versorgt.",
  "success-passt": "Passt, wackelt und hat Luft. Nächste Schicht?",
  "success-geschmiert": "Läuft wie geschmiert! Ich komme mit dem Mitschreiben kaum nach.",
  "success-arbeitslos": "Wieder ein Häkchen mehr. Du machst mich noch arbeitslos!",
  "dashboard-intro": "Dein Dashboard auf einen Blick. Hier laufen die Informationen aus deiner Planung zusammen. Ich zeige dir jetzt nur die Bereiche, die auf diesem Dashboard wirklich sichtbar sind.",
  "dashboard-countdown-dated": "Countdown bis zum Event. Hier siehst du den Zeitraum der aktuellen Veranstaltung und den Countdown. Das Datum kommt direkt aus den Eventdaten und aktualisiert sich automatisch.",
  "dashboard-countdown-empty": "Zeitraum für den Countdown festlegen. Hier erscheint der Countdown, sobald du in den Eventdaten einen Start- und bei mehrtägigen Veranstaltungen auch einen Endtermin speicherst.",
  "dashboard-priorities-attention": "Was jetzt Aufmerksamkeit braucht. Diese Karten zeigen nur konkrete Warnungen oder offene Punkte, zum Beispiel unbesetzte Schichten, Ausfälle oder offene Vorbereitungen. Ein Klick führt direkt in den passenden Bereich.",
  "dashboard-priorities-clear": "Keine dringenden Punkte. Hier werden später nur Punkte eingeblendet, die unmittelbar Aufmerksamkeit brauchen. Sobald es offene Schichten, Konflikte oder Aufgaben gibt, erscheinen sie automatisch an dieser Stelle.",
  "dashboard-deadlines": "Datierte Vorbereitungsaufgaben. Diese Übersicht erscheint, wenn Vorbereitungsaufgaben ein Fälligkeitsdatum haben. Du siehst die nächsten Termine zuerst und öffnest per Klick direkt die zugehörige Aufgabe.",
  "dashboard-helpers-active": "Helferstatus je Festivaltag. Hier erkennst du pro Veranstaltungstag Besetzung und Bedarf, Rückmeldungen, Erstkontakte und Verpflegungsspenden. Klickbare Werte führen in die bereits passend gefilterte Helfer- oder Einsatzplanansicht.",
  "dashboard-helpers-empty": "Helferstatus entsteht mit deiner Planung. Sobald du Helfer anlegst und Schichten mit Bedarf planst, erscheinen hier Besetzung, Rückmeldungen und Erstkontakte. Erfasste Kuchen- und Salatspenden werden daneben automatisch zusammengefasst.",
  "dashboard-details-active": "Wer macht was – und wer ist frei? Links siehst du Verantwortlichkeiten nach Ansprechpartnern. Rechts zeigt die Helferauslastung alle eingeteilten Schichten je Tag. Ein Klick auf einen Namen oder Wert öffnet die passende gefilterte Einsatzplanung.",
  "dashboard-details-empty": "Details wachsen mit den Einträgen. Hier entstehen zwei Übersichten, sobald Ansprechpartner, Helfer und Schichten gepflegt sind: Zuständigkeiten auf der linken Seite und die tägliche Helferauslastung auf der rechten Seite.",
  "dashboard-map-active": "Live-Standortkarte nutzen. Diese Karte verbindet Orte mit Vorbereitung, Schichten und Material. Die Farben zeigen den jeweiligen Stand, und ein Klick auf einen Marker filtert den passenden Planungsbereich.",
  "dashboard-map-empty": "Standortkarte später aktivieren. Sobald du unter Orte und Standorte mindestens einen Standort mit Koordinaten anlegst, wird hier unten automatisch die Live-Standortkarte mit den zugehörigen Planungsinformationen eingeblendet.",
  "dashboard-complete": "Alles im Blick! Du weißt jetzt, wo das Dashboard den aktuellen Planungsstand zeigt – und welche Eingaben die einzelnen Übersichten füllen.",

  "helpers-intro": "Neue Helfer sicher anlegen. Ich führe dich direkt auf der echten Oberfläche durch die Anlage – vom Namen bis zum passenden Zeitfenster.",
  "helpers-person": "Mit einem eindeutigen Namen beginnen. Der Name ist die einzige Pflichtangabe und sorgt dafür, dass das Planungsteam die Person in Helferliste, Einsatzplan und persönlicher PDF eindeutig wiederfindet. Diese Führung öffnet nur die leere Anlage – sie speichert nichts.",
  "helpers-contact": "Kontaktwege für Rückfragen ergänzen. Ansprechpartner und Telefonnummer sind optional, aber sehr hilfreich: Das Team weiß, wer zuständig ist und kann den Helfer bei einer Rückfrage oder kurzfristigen Änderung direkt erreichen.",
  "helpers-details": "Hinweise und Begleitung festhalten. Besondere Hinweise erscheinen später in der persönlichen Helfer-PDF. Eine Begleitung wird im Einsatzplan sichtbar, damit das Team bei der Schichtplanung genau weiß, wer zusätzlich mitkommt.",
  "helpers-donation": "Spende direkt mit erfassen. Wenn jemand Kuchen, Salat, Snacks oder eine andere Spende zusagt, öffnet dieses Feld die vollständige Spendenerfassung. So bleiben Verpflegung, Eigenschaften und Absprachen von Anfang an beim richtigen Helfer nachvollziehbar.",
  "helpers-save": "Erst speichern – dann kann das Team planen. Mit Helfer anlegen oder Helfer und Spende anlegen wird die Person vollständig übernommen. Erst danach steht sie dem Planungsteam im Einsatzplan zur Auswahl. Für diese Erklärung musst du den Button nicht drücken.",
  "helpers-availability": "Tage und Zeitfenster realistisch festlegen. An einem bereits angelegten Helfer siehst du die Tagesverfügbarkeiten. Ja bedeutet: an diesem Tag grundsätzlich planbar. Nein schützt vor einer falschen Einteilung. Mit einem Zeitfenster gibst du an, wann die Person wirklich kann.",
  "helpers-plan-fill": "Das Team füllt danach die passenden Schichten. Sobald Helfer gespeichert und Verfügbarkeiten gepflegt sind, teilt das Planungsteam sie im Einsatzplan den offenen Schichten zu. Tageszeichen, Zeitfenster, Begleitungen und bereits belegte Einsätze helfen dabei, Überlappungen zu vermeiden.",
  "helpers-feedback": "Erst die Antwort macht die Besetzung verbindlich. Antwortet der Helfer, trägt das Team Helfen: Ja oder Nein ein und setzt die Bestätigung passend zur Rückmeldung. Nur bestätigte Zusagen machen sichtbar, welche Schichten wirklich sicher sind.",
  "helpers-symbols-offer": "Geschafft! Du hast einen Helfer angelegt und die Verfügbarkeit kennengelernt. Soll ich dir auch noch die Symbole direkt an diesem Helfer erklären?",
  "helpers-action-donation": "Geschenk: Spenden dieses Helfers. Das Geschenk ganz links öffnet die Spendenübersicht genau für diese Person. Dort lassen sich Kuchen, Salate oder Snacks mit Eigenschaften und Hinweisen erfassen und später wiederfinden.",
  "helpers-action-whatsapp": "Nach vollständiger Planung per WhatsApp anfragen. Ist der Einsatzplan für diesen Helfer fertig, öffnet das grüne Symbol die passende WhatsApp-Vorlage. Die Nachricht kann den persönlichen Helferplan mit PDF-Link enthalten und bittet verbindlich um Rückmeldung. In dieser Tour wird nichts versendet.",
  "helpers-action-pdf": "Persönlichen Helferplan als PDF bereitstellen. Das blaue Symbol erzeugt die persönliche Aufgaben-PDF mit Einsätzen, Hinweisen und Verfügbarkeiten. Sie kann nach der Planung heruntergeladen oder über die WhatsApp-Vorlage verlinkt werden. In dieser Erklärung wird nichts heruntergeladen.",
  "helpers-action-edit": "Daten später sauber nachpflegen. Der Stift öffnet die Bearbeitung. Telefonnummer, Ansprechpartner, Hinweis, Begleitung und Verfügbarkeiten können hier später ergänzt oder geändert werden, ohne den bisherigen Einsatzplan zu verlieren.",
  "helpers-action-delete": "Der Papierkorb wird nur rot und anklickbar angezeigt, wenn dieser Helfer gelöscht werden darf. Bei geschützten oder eingeteilten Personen bleibt er grau. So kann nichts versehentlich verloren gehen.",
  "helpers-complete": "Der Ablauf ist klar: Helfer speichern, Verfügbarkeiten pflegen, Schichten passend füllen, den persönlichen Plan senden und die Antwort verbindlich eintragen – so bleibt der Einsatzplan zuverlässig.",

  "contacts-intro": "Ansprechpartner von Anfang an pflegen. Ansprechpartner sind deine verlässlichen Kontaktpersonen für Teams, Helfer und PDFs. Ich führe dich kurz durch die Stammdatenanlage.",
  "contacts-name": "Name eindeutig eintragen. Trage zuerst den Namen ein. Diese Angabe ist erforderlich und erscheint später bei Zuordnungen, in Listen und in persönlichen Unterlagen.",
  "contacts-details": "E-Mail und Rufnummer ergänzen. E-Mail-Adresse und Rufnummer sind optional, aber für Rückfragen besonders hilfreich. Ein persönlicher Zugang wird bewusst getrennt unter Schutz und Protokoll eingerichtet.",
  "contacts-save": "Ansprechpartner hinzufügen. Klicke auf den markierten Button. Danach steht die Person direkt für Helfer, Aufgaben und Zuständigkeiten zur Auswahl bereit.",
  "contacts-complete": "Geschafft! Der Ansprechpartner ist angelegt und kann jetzt überall in der Planung zugeordnet werden.",

  "donations-intro": "Spenden übersichtlich erfassen. Kuchen, Salate und andere Verpflegungsspenden werden hier sauber mit Spender, Eigenschaften und Abgabe organisiert.",
  "donations-donor": "Spender zuordnen. Wähle einen bestehenden Helfer aus oder trage einen Namen frei ein. So bleibt nachvollziehbar, von wem die Spende kommt.",
  "donations-item": "Spende und Kategorie festlegen. Beschreibe kurz, was mitgebracht wird, und wähle die passende Kategorie. So bleibt der Überblick über Kuchen, Salate, Desserts und Sonstiges erhalten.",
  "donations-traits": "Allergene, Abgabe und Hinweise. Kennzeichne bei Bedarf vegan, glutenfrei, laktosefrei, Nüsse oder fleischhaltig. Abgabeort, Zeitpunkt und ein freier Hinweis helfen der Verpflegung am Veranstaltungstag.",
  "donations-save": "Spende speichern. Mit dem markierten Speichern-Button wird die Spende in die Übersicht übernommen und zählt automatisch für die aktuelle Veranstaltung.",
  "donations-complete": "Prima! Die Spende ist erfasst und bleibt für Verpflegung und Helferteam transparent sichtbar.",

  "finances-intro": "Finanzen einfach im Blick behalten. Hier werden Einnahmen und Ausgaben nach Kategorien getrennt geführt. Der Saldo wird für dich automatisch berechnet.",
  "finances-category": "Kostenart anlegen. Trage eine klare Kategorie ein, zum Beispiel Startgelder, Catering, Technik oder Sponsoring. Mit dem Button daneben wird die neue Zeile angelegt.",
  "finances-values": "Einnahmen und Ausgaben eintragen. In jeder Kategorie gibst du Einnahmen und Ausgaben ein. Die Werte werden beim Verlassen des Feldes gespeichert; die Differenz zeigt sofort den aktuellen Stand.",
  "finances-balance": "Saldo gemeinsam prüfen. Ganz unten fasst der Saldo alle Kategorien zusammen. So erkennst du schnell, ob deine Veranstaltung finanziell im Plan liegt.",
  "finances-complete": "Alles klar! Du weißt jetzt, wo Kategorien, Einzelwerte und der gesamte Saldo zusammenkommen.",

  "pdf-intro": "Passende PDFs gezielt erstellen. In der PDF-Ausgabe erzeugst du persönliche Helferunterlagen, Ansprechpartnerübersichten und gefilterte Einsatzpläne aus den realen Planungsdaten.",
  "pdf-helpers": "Helfer-PDFs bündeln. Wähle bei Bedarf einen Ansprechpartner aus. Anschließend erzeugst du entweder alle Helfer-PDFs als ZIP oder nur die passenden Unterlagen für diese Person.",
  "pdf-plan": "Einsatzplan filtern und drucken. Für den Einsatzplan wählst du Tag, Bereiche, Status und bei Bedarf Ansprechpartner. Das PDF enthält nur die Auswahl, die du wirklich brauchst.",
  "pdf-config": "Vorlage pro Veranstaltung pflegen. Administratoren können hier Logo, Titel, Zusatzspalten, Fußzeilen und WhatsApp-Vorlagen für die aktuell gewählte Veranstaltung konfigurieren. Andere sehen die fertigen PDFs weiterhin unverändert.",
  "pdf-complete": "Fertig! Damit kannst du genau die Unterlagen erzeugen, die dein Team gerade braucht.",

  "security-intro": "Schutz und Protokoll sicher nutzen. Dieser Bereich ist für Administratoren. Hier werden Zugänge, Notfallmaßnahmen und nachvollziehbare Protokolle getrennt und sicher verwaltet.",
  "security-accesses": "Planungsteam-Zugänge verwalten. Hier legst du gezielt Zugänge, Eventfreigaben und Bereichsrechte an. Ein Zugang ist erst nach der passenden Freigabe in der aktuellen Veranstaltung wirksam.",
  "security-audit": "Änderungen nachvollziehen. Das Logbuch trennt Sicherheitsereignisse, Aktivitäten sowie Datei- und Importvorgänge. So lässt sich jederzeit nachvollziehen, was wann passiert ist.",
  "security-emergency": "Notfallmaßnahmen bewusst einsetzen. Der globale Notfall-Stopp sperrt alle Planungsteam-Zugänge sofort. Der Gefahrenbereich löscht Planungsdaten des gewählten Jahres – nutze beides nur bewusst und nach Prüfung.",
  "security-complete": "Gut! Du weißt jetzt, wo du Zugänge sicher verwaltest und den Verlauf kontrollierst.",

  "help-intro": "Im Hilfe-Center schnell zurechtfinden. Hier findest du kurze Anleitungen für die gesamte Planung – von der ersten Orientierung bis zu PDFs, Rechten und Sicherungen.",
  "help-search": "Direkt nach einem Begriff suchen. Tippe einfach ein Stichwort wie Helfer, Einsatzplan, Material, PDF oder Passwort ein. Die sichtbaren Kapitel passen sich sofort an.",
  "help-filters": "Hilfe nach Rolle filtern. Mit den Rollenfiltern blendest du Inhalte für alle, für das Planungsteam oder für Administratoren ein. So bleibt die Anleitung passend zu deinen Rechten.",
  "help-chapters": "Kapitel öffnen und direkt weiterarbeiten. Öffne das passende Kapitel, lies die kompakten Schritte und nutze die Links direkt zum jeweiligen Arbeitsbereich. Klemmi bleibt auch dort wieder für dich erreichbar.",
  "help-complete": "Geschafft! Jetzt weißt du, wie du in der Hilfe schnell zur passenden Antwort und direkt weiter zur Arbeit kommst.",

  "plan-intro": "Schichten anlegen und Besetzung füllen. Ich begleite dich zuerst durch die Schichtanlage und zeige dir danach direkt an der neuen Kachel, wie du passende Helfer sicher einteilst.",
  "plan-basics": "Tag und Personalbedarf festlegen. Wähle den passenden Eventtag und die Zahl der benötigten Helferplätze. So wird Unterbesetzung später sofort sichtbar.",
  "plan-task": "Bereich und Aufgabe benennen. Ein klarer Bereich und eine konkrete Aufgabe helfen dem Team, die Schicht in der Liste und auf dem Gelände sofort einzuordnen.",
  "plan-time": "Zeitfenster und Besonderheiten ergänzen. Trage Beginn und Ende ein, wenn die Schicht zeitgebunden ist. Ort, Hinweise und flexible Belegung kannst du nach Bedarf ergänzen.",
  "plan-save": "Schicht speichern. Klicke auf den markierten Speichern-Button. Erst dein Klick legt die Schicht im Einsatzplan an.",
  "plan-created": "Neue Schicht in der Kachel finden. Die neue Schicht erscheint als Kachel mit Bedarf und Fortschrittsbalken. Links stehen die Eingeteilten, rechts wählst du passende Helfer aus.",
  "plan-candidates": "Statuszeichen vor dem Namen lesen. Neu heißt: noch in keiner Schicht eingeteilt. Die Tagessegmente zeigen Grün für frei, Gelb für an diesem Tag schon belegt und Rot für nicht verfügbar. Die Uhr steht für ein Zeitfenster; das Familiensymbol bedeutet, dass eine Begleitung mitkommt.",
  "plan-assign": "Passende Helfer gesammelt zuordnen. Setze vorne bei allen passenden Personen ein Häkchen und übernimm die Auswahl gesammelt. Ein Klick auf den Namen öffnet Hinweise, Verfügbarkeit und bisherige Einsätze.",
  "plan-complete": "Besetzung im Griff! Du erkennst jetzt neue Helfer, Tagesstatus, Begleitungen und bestehende Einsätze – und kannst freie Plätze gesammelt füllen.",

  "preparation-intro": "Vorbereitungsaufgaben sicher planen. Ich zeige dir die echte Aufgabenanlage: Aufgabe formulieren, Zuständigkeit und Termin festlegen und den ersten Stand sauber festhalten.",
  "preparation-task": "Aufgabe klar formulieren. Beschreibe konkret, was erledigt werden soll. Bereich und Ort helfen, die Aufgabe später schnell wiederzufinden.",
  "preparation-details": "Verantwortung und Frist zuordnen. Wähle bei Bedarf eine verantwortliche Person und einen Termin. Beides kann später jederzeit angepasst werden.",
  "preparation-logbook": "Ersten Stand notieren. Im Logbuch gehören wichtige Hinweise, Absprachen und nächste Schritte. Der Eintrag bleibt nachvollziehbar gespeichert.",
  "preparation-save": "Aufgabe speichern. Klicke auf den markierten Speichern-Button. Erst dein Klick legt die Vorbereitungsaufgabe an.",
  "preparation-complete": "Vorbereitungsaufgabe angelegt! Die Aufgabe steht jetzt in der Vorbereitung. Zuständige, Frist und Logbuch kannst du jederzeit weiterführen.",

  "postprocessing-intro": "Nachbereitung verbindlich festhalten. Ich zeige dir die echte Nachbereitungsanlage: Aufgabe benennen, Verantwortliche und Termin einordnen und Übergaben dokumentieren.",
  "postprocessing-task": "Aufgabe konkret benennen. Schreibe kurz und eindeutig, was nach dem Event erledigt werden muss – zum Beispiel Rückgabe, Abbau oder Abrechnung.",
  "postprocessing-details": "Verantwortung und Termin setzen. Ordne die Aufgabe bei Bedarf einer Person zu und lege eine Frist fest. Beides darf später angepasst werden.",
  "postprocessing-logbook": "Übergabe und Hinweise dokumentieren. Im Logbuch kommen wichtige Hinweise, Ergebnisse und nächste Schritte. So bleibt der Abschluss nachvollziehbar.",
  "postprocessing-save": "Aufgabe speichern. Klicke auf den markierten Speichern-Button. Erst dein Klick legt die Nachbereitungsaufgabe an.",
  "postprocessing-complete": "Nachbereitungsaufgabe angelegt! Die Aufgabe steht jetzt in der Nachbereitung. So bleiben Abbau, Rückgaben und offene Punkte für das Team sichtbar.",

  "materials-intro": "Material schnell und sauber erfassen. Ich zeige dir die echte Materialanlage: Artikel benennen, Menge eintragen und Beschaffung oder Einsatzort eindeutig festhalten.",
  "materials-name": "Artikel klar benennen. Trage zuerst ein, was benötigt wird – zum Beispiel Bierzeltgarnitur, Kabeltrommel oder Kaffeebecher.",
  "materials-details": "Menge und Einordnung festhalten. Menge, Einheit und Kategorie machen den Bedarf nachvollziehbar. Ort und Beschaffungsstand kannst du bei Bedarf direkt ergänzen.",
  "materials-save": "Materialposition speichern. Klicke auf den markierten Speichern-Button. Erst dein Klick legt den Artikel tatsächlich im Materialplan an.",
  "materials-complete": "Materialposition angelegt! Der Artikel ist jetzt im Materialplan. Status, Verantwortliche und Ort kannst du später jederzeit ergänzen oder anpassen.",

  "locations-intro": "Orte und Standorte sauber anlegen. Ich zeige dir die echte Standortanlage: Namen vergeben, Koordinaten eintragen und den Ort anschließend in Schichten, Material und Vorbereitung verwenden.",
  "locations-name": "Ort eindeutig benennen. Gib dem Standort einen Namen, den das Team auf Anhieb versteht – zum Beispiel VP acht, Pumptrack oder Kuchenstand.",
  "locations-coordinates": "Position auf der Karte festlegen. Breiten- und Längengrad positionieren den Standort auf der Live-Karte. Ein Marker-Logo darunter ist optional.",
  "locations-save": "Standort speichern. Klicke auf den markierten Button. Erst dein Klick legt den Standort wirklich an.",
  "locations-complete": "Standort angelegt! Der Ort steht jetzt in Schichten, Vorbereitung und Material zur Auswahl und erscheint auf der Live-Standortkarte.",
} as const;

export type KlemmiAudioId = keyof typeof KLEMMI_AUDIO_SCRIPTS;

/**
 * Beim bewussten Öffnen einer Klemmi-Tour wählt der Browser genau einen dieser
 * kurzen Einstiege. Der letzte Clip wird ausgeschlossen, damit sich kein
 * Einstieg unmittelbar wiederholt.
 */
export const KLEMMI_OPENING_AUDIO_IDS = [
  "opening-clears-throat",
  "opening-cough",
  "opening-sniff",
  "opening-ach-herrje",
  "opening-servus",
  "opening-gruess-gott",
  "opening-hallo",
  "opening-na-dann",
  "opening-auf-gehts",
  "opening-moin",
  "opening-halloechen",
  "opening-tadaa",
  "opening-na-schau-an",
  "opening-guten-tag",
  "opening-klingeling",
  "opening-hmm",
  "opening-jawohl",
  "opening-aha",
  "opening-hey-ho",
  "opening-na-endlich",
  "opening-hoi",
  "opening-bitte-sehr",
  "opening-wir-packen-das",
  "opening-einen-moment",
  "opening-hopp-hopp",
  "opening-zack",
  "opening-lass-uns-schauen",
  "opening-alles-klar",
  "opening-ganz-entspannt",
  "opening-wunderbar",
] as const satisfies readonly KlemmiAudioId[];

/**
 * Neue Sprachfassungen erhalten eine eigene URL. Dadurch kann kein Browser
 * trotz langer Cache-Zeit versehentlich eine vorherige Klemmi-Aufnahme spielen.
 */
const KLEMMI_AUDIO_REVISIONS: Partial<Record<KlemmiAudioId, string>> = {
  "helpers-person": "20260928-informational-tour-v1",
  "helpers-contact": "20260928-informational-tour-v1",
  "helpers-details": "20260928-informational-tour-v1",
  "helpers-donation": "20260928-informational-tour-v1",
  "helpers-save": "20260928-informational-tour-v1",
  "helpers-availability": "20260928-informational-tour-v1",
  "helpers-plan-fill": "20260928-informational-tour-v1",
  "helpers-feedback": "20260928-informational-tour-v1",
  "helpers-action-donation": "20260928-informational-tour-v1",
  "helpers-action-whatsapp": "20260928-informational-tour-v1",
  "helpers-action-pdf": "20260928-informational-tour-v1",
  "helpers-action-edit": "20260928-informational-tour-v1",
  "helpers-action-delete": "20260928-informational-tour-v1",
  "helpers-complete": "20260928-informational-tour-v1",
  "first-login-intro": "20260927-joke-v2",
  "first-login-co-admin": "20260927-joke-v2",
  "login-warmgelaufen": "20260927-daily-greetings-v1",
  "login-chaos": "20260927-daily-greetings-v1",
  "login-ehrenamt": "20260927-daily-greetings-v1",
  "login-aermel": "20260927-daily-greetings-v1",
  "login-kaffee": "20260927-daily-greetings-v1",
  "login-tabellen": "20260927-daily-greetings-v1",
  "login-druecker": "20260927-daily-greetings-v1",
  "login-noch-eins": "20260927-daily-greetings-v1",
  "login-datenbank": "20260927-daily-greetings-v1",
  "login-system": "20260927-daily-greetings-v1",
  "login-superhelden": "20260927-daily-greetings-v1",
  "login-roter-teppich": "20260927-daily-greetings-v1",
  "idle-vorstehhund": "20260927-daily-greetings-v1",
  "idle-kaffee": "20260927-daily-greetings-v1",
  "idle-standbild": "20260927-daily-greetings-v1",
  "idle-wuerstchenbude": "20260927-daily-greetings-v1",
  "idle-singen": "20260927-daily-greetings-v1",
  "error-halt-stopp": "20260927-daily-greetings-v1",
  "error-fast-perfekt": "20260927-daily-greetings-v1",
  "error-zauberei": "20260927-daily-greetings-v1",
  "error-rotes-feld": "20260927-daily-greetings-v1",
  "error-verrats-keinem": "20260927-daily-greetings-v1",
  "error-kleingedrucktes": "20260927-daily-greetings-v1",
  "error-knapp-vorbei": "20260927-daily-greetings-v1",
  "error-schranke": "20260927-daily-greetings-v1",
  "success-zack": "20260927-daily-greetings-v1",
  "success-boom": "20260927-daily-greetings-v1",
  "success-volltreffer": "20260927-daily-greetings-v1",
  "success-reibungslos": "20260927-daily-greetings-v1",
  "success-baem": "20260927-daily-greetings-v1",
  "success-leerstand": "20260927-daily-greetings-v1",
  "success-bilderbuch": "20260927-daily-greetings-v1",
  "success-bingo": "20260927-daily-greetings-v1",
  "success-high-five": "20260927-daily-greetings-v1",
  "success-passt": "20260927-daily-greetings-v1",
  "success-geschmiert": "20260927-daily-greetings-v1",
  "success-arbeitslos": "20260927-daily-greetings-v1",
  "dashboard-intro": "20260927-dashboard-tour-v1",
  "dashboard-complete": "20260927-dashboard-tour-v1",
  "plan-intro": "20260927-assignment-guide-v1",
  "plan-created": "20260927-assignment-guide-v1",
  "plan-candidates": "20260927-assignment-guide-v1",
  "plan-assign": "20260927-assignment-guide-v1",
  "plan-complete": "20260927-assignment-guide-v1",
};

export function isKlemmiAudioId(value: string): value is KlemmiAudioId {
  return value in KLEMMI_AUDIO_SCRIPTS;
}

export function klemmiAudioUrl(id: KlemmiAudioId) {
  const revision = KLEMMI_AUDIO_REVISIONS[id];
  return revision ? `${KLEMMI_AUDIO_ROUTE}/${id}?v=${revision}` : `${KLEMMI_AUDIO_ROUTE}/${id}`;
}
